rem ============================================================================
rem LICENSE
rem   Copyright (c) 2026 Oracle and/or its affiliates.
rem   Licensed under the Universal Permissive License (UPL), Version 1.0
rem   https://oss.oracle.com/licenses/upl/
rem
rem NAME
rem   dbms_scheduler_monitor_tools.sql
rem
rem DESCRIPTION
rem   Installer script for DBMS_SCHEDULER monitoring and performance tools.
rem
rem RELEASE VERSION
rem   1.0
rem
rem RELEASE DATE
rem   19-May-2026
rem ============================================================================

SET SERVEROUTPUT ON
SET VERIFY OFF

VAR v_schema VARCHAR2(128)
EXEC :v_schema := '&SCHEMA_NAME';

CREATE OR REPLACE PROCEDURE initialize_scheduler_monitoring(
  p_install_schema_name IN VARCHAR2
)
IS
  l_schema_name VARCHAR2(128);

  TYPE priv_list_t IS VARRAY(20) OF VARCHAR2(4000);
  l_priv_list CONSTANT priv_list_t := priv_list_t(
    'DBMS_CLOUD_AI_AGENT',
    'DBMS_CLOUD_AI',
    'DBMS_CLOUD'
  );

  PROCEDURE execute_grants(p_schema IN VARCHAR2, p_objects IN priv_list_t) IS
    l_session_user VARCHAR2(128);
  BEGIN
    l_session_user := SYS_CONTEXT('USERENV', 'SESSION_USER');

    IF UPPER(p_schema) = UPPER(l_session_user) THEN
      DBMS_OUTPUT.PUT_LINE('Skipping grants for schema ' || p_schema ||
                           ' (same as session user).');
      RETURN;
    END IF;

    FOR i IN 1 .. p_objects.COUNT LOOP
      BEGIN
        EXECUTE IMMEDIATE 'GRANT EXECUTE ON ' || p_objects(i) || ' TO ' || p_schema;
      EXCEPTION
        WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('Warning: failed to grant ' || p_objects(i) ||
                               ' to ' || p_schema || ' - ' || SQLERRM);
      END;
    END LOOP;
  END execute_grants;
BEGIN
  l_schema_name := DBMS_ASSERT.SIMPLE_SQL_NAME(p_install_schema_name);
  execute_grants(l_schema_name, l_priv_list);

  BEGIN
    EXECUTE IMMEDIATE
      'CREATE TABLE ' || l_schema_name || '.SCHED_MONITOR_LOG$(
         id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         logged_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
         operation_name   VARCHAR2(200),
         duration_ms      NUMBER,
         status           VARCHAR2(30),
         error_message    CLOB
       )';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -955 THEN
        RAISE;
      END IF;
  END;

  DBMS_OUTPUT.PUT_LINE('initialize_scheduler_monitoring completed for schema ' || l_schema_name);
END initialize_scheduler_monitoring;
/

BEGIN
  initialize_scheduler_monitoring(:v_schema);
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER SESSION SET CURRENT_SCHEMA = ' || :v_schema;
END;
/

CREATE OR REPLACE PACKAGE scheduler_monitoring AUTHID CURRENT_USER AS
  FUNCTION format_duration(p_seconds IN NUMBER) RETURN VARCHAR2;

  FUNCTION get_database_current_time RETURN CLOB;

  FUNCTION list_all_jobs(
    p_job_name_pattern IN VARCHAR2 DEFAULT NULL,
    p_top_n            IN NUMBER DEFAULT 1000
  ) RETURN CLOB;

  FUNCTION list_running_jobs(
    p_owner            IN VARCHAR2 DEFAULT NULL,
    p_job_name_pattern IN VARCHAR2 DEFAULT NULL,
    p_top_n            IN NUMBER DEFAULT 200
  ) RETURN CLOB;

  FUNCTION list_job_history(
    p_start_time       IN VARCHAR2,
    p_end_time         IN VARCHAR2,
    p_owner            IN VARCHAR2 DEFAULT NULL,
    p_job_name_pattern IN VARCHAR2 DEFAULT NULL,
    p_status           IN VARCHAR2 DEFAULT NULL,
    p_top_n            IN NUMBER DEFAULT 1000
  ) RETURN CLOB;

  FUNCTION get_job_details(
    p_owner    IN VARCHAR2,
    p_job_name IN VARCHAR2
  ) RETURN CLOB;

  FUNCTION analyze_cpu_by_job(
    p_start_time       IN VARCHAR2,
    p_end_time         IN VARCHAR2,
    p_owner            IN VARCHAR2 DEFAULT NULL,
    p_job_name_pattern IN VARCHAR2 DEFAULT NULL,
    p_top_n            IN NUMBER DEFAULT 20
  ) RETURN CLOB;

  FUNCTION analyze_load_by_job(
    p_start_time       IN VARCHAR2,
    p_end_time         IN VARCHAR2,
    p_owner            IN VARCHAR2 DEFAULT NULL,
    p_job_name_pattern IN VARCHAR2 DEFAULT NULL,
    p_granularity      IN VARCHAR2 DEFAULT 'HOUR'
  ) RETURN CLOB;

  FUNCTION compare_jobs(
    p_start_time IN VARCHAR2,
    p_end_time   IN VARCHAR2,
    p_owner      IN VARCHAR2,
    p_job_a      IN VARCHAR2,
    p_job_b      IN VARCHAR2
  ) RETURN CLOB;

  FUNCTION identify_hotspots(
    p_start_time  IN VARCHAR2,
    p_end_time    IN VARCHAR2,
    p_top_n       IN NUMBER DEFAULT 20,
    p_min_elapsed IN NUMBER DEFAULT 0,
    p_min_cpu     IN NUMBER DEFAULT 0
  ) RETURN CLOB;

  FUNCTION detect_failures(
    p_start_time       IN VARCHAR2,
    p_end_time         IN VARCHAR2,
    p_owner            IN VARCHAR2 DEFAULT NULL,
    p_job_name_pattern IN VARCHAR2 DEFAULT NULL,
    p_top_n            IN NUMBER DEFAULT 100
  ) RETURN CLOB;

  FUNCTION summarize_scheduler_health(
    p_start_time  IN VARCHAR2,
    p_end_time    IN VARCHAR2,
    p_owner       IN VARCHAR2 DEFAULT NULL,
    p_top_n       IN NUMBER DEFAULT 10
  ) RETURN CLOB;

  FUNCTION generate_charts(
    p_start_time       IN VARCHAR2,
    p_end_time         IN VARCHAR2,
    p_owner            IN VARCHAR2 DEFAULT NULL,
    p_job_name_pattern IN VARCHAR2 DEFAULT NULL,
    p_granularity      IN VARCHAR2 DEFAULT 'HOUR',
    p_top_n            IN NUMBER DEFAULT 10
  ) RETURN CLOB;

  FUNCTION export_tables(
    p_start_time       IN VARCHAR2,
    p_end_time         IN VARCHAR2,
    p_owner            IN VARCHAR2 DEFAULT NULL,
    p_job_name_pattern IN VARCHAR2 DEFAULT NULL,
    p_top_n            IN NUMBER DEFAULT 500
  ) RETURN CLOB;
END scheduler_monitoring;
/

CREATE OR REPLACE PACKAGE BODY scheduler_monitoring AS
  PROCEDURE write_log(
    p_operation_name IN VARCHAR2,
    p_start_ts       IN TIMESTAMP,
    p_status         IN VARCHAR2,
    p_error_message  IN CLOB DEFAULT NULL
  );

  FUNCTION parse_ts(p_text IN VARCHAR2) RETURN TIMESTAMP WITH TIME ZONE IS
  BEGIN
    IF p_text IS NULL THEN
      RETURN NULL;
    END IF;

    BEGIN
      RETURN TO_TIMESTAMP_TZ(p_text, 'YYYY-MM-DD"T"HH24:MI:SS.FF TZH:TZM');
    EXCEPTION
      WHEN OTHERS THEN
        BEGIN
          RETURN TO_TIMESTAMP_TZ(p_text, 'YYYY-MM-DD"T"HH24:MI:SS TZH:TZM');
        EXCEPTION
          WHEN OTHERS THEN
            RETURN TO_TIMESTAMP_TZ(
                     p_text || ' ' || TO_CHAR(SYSTIMESTAMP, 'TZH:TZM'),
                     'YYYY-MM-DD HH24:MI:SS TZH:TZM'
                   );
        END;
    END;
  END parse_ts;

  FUNCTION clamp_top_n(p_top_n IN NUMBER, p_default IN NUMBER, p_max IN NUMBER) RETURN NUMBER IS
  BEGIN
    RETURN LEAST(GREATEST(NVL(p_top_n, p_default), 1), p_max);
  END clamp_top_n;

  FUNCTION sanitize_granularity(p_val IN VARCHAR2) RETURN VARCHAR2 IS
    l_val VARCHAR2(20) := UPPER(TRIM(NVL(p_val, 'HOUR')));
  BEGIN
    IF l_val NOT IN ('MINUTE', 'HOUR', 'DAY') THEN
      RETURN 'HOUR';
    END IF;
    RETURN l_val;
  END sanitize_granularity;

  FUNCTION sanitize_status(p_val IN VARCHAR2) RETURN VARCHAR2 IS
    l_val VARCHAR2(40) := UPPER(TRIM(p_val));
  BEGIN
    IF l_val IS NULL THEN
      RETURN NULL;
    END IF;
    IF l_val IN ('SUCCEEDED','FAILED','RUNNING','RETRY SCHEDULED','STOPPED','BROKEN') THEN
      RETURN l_val;
    END IF;
    RETURN NULL;
  END sanitize_status;

  FUNCTION format_duration(p_seconds IN NUMBER) RETURN VARCHAR2 IS
    l_secs NUMBER := NVL(p_seconds, 0);
  BEGIN
    IF l_secs < 60 THEN
      RETURN TO_CHAR(ROUND(l_secs, 3)) || ' sec';
    ELSIF l_secs < 3600 THEN
      RETURN TO_CHAR(ROUND(l_secs / 60, 3)) || ' min';
    ELSIF l_secs < 86400 THEN
      RETURN TO_CHAR(ROUND(l_secs / 3600, 3)) || ' hr';
    ELSE
      RETURN TO_CHAR(ROUND(l_secs / 86400, 3)) || ' day';
    END IF;
  END format_duration;

  FUNCTION get_database_current_time RETURN CLOB IS
    l_json CLOB;
  BEGIN
    SELECT JSON_OBJECT(
      'database_systimestamp' VALUE TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DD\"T\"HH24:MI:SS.FF TZH:TZM'),
      'database_sysdate' VALUE TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'),
      'session_timezone' VALUE SESSIONTIMEZONE,
      'dbtimezone' VALUE DBTIMEZONE
    )
    INTO l_json
    FROM dual;

    RETURN l_json;
  EXCEPTION
    WHEN OTHERS THEN
      RETURN JSON_OBJECT('status' VALUE 'error', 'message' VALUE SQLERRM);
  END get_database_current_time;

  FUNCTION list_all_jobs(
    p_job_name_pattern IN VARCHAR2 DEFAULT NULL,
    p_top_n            IN NUMBER DEFAULT 1000
  ) RETURN CLOB IS
    l_start_ts TIMESTAMP := SYSTIMESTAMP;
    l_json CLOB;
    l_top_n NUMBER := clamp_top_n(p_top_n, 1000, 10000);
  BEGIN
    SELECT JSON_OBJECT(
      'summary' VALUE (
        SELECT JSON_OBJECT(
          'owner' VALUE SYS_CONTEXT('USERENV','CURRENT_SCHEMA'),
          'total_jobs' VALUE COUNT(*),
          'enabled_jobs' VALUE SUM(CASE WHEN enabled = 'TRUE' THEN 1 ELSE 0 END),
          'disabled_jobs' VALUE SUM(CASE WHEN enabled = 'FALSE' THEN 1 ELSE 0 END),
          'running_jobs' VALUE SUM(CASE WHEN state = 'RUNNING' THEN 1 ELSE 0 END),
          'failed_state_jobs' VALUE SUM(CASE WHEN state = 'FAILED' THEN 1 ELSE 0 END),
          'broken_jobs' VALUE SUM(CASE WHEN state = 'BROKEN' THEN 1 ELSE 0 END)
        )
        FROM USER_SCHEDULER_JOBS
        WHERE (p_job_name_pattern IS NULL OR job_name LIKE UPPER(p_job_name_pattern))
      ),
      'returned_rows' VALUE (
        SELECT COUNT(*)
        FROM (
          SELECT 1
          FROM USER_SCHEDULER_JOBS
          WHERE (p_job_name_pattern IS NULL OR job_name LIKE UPPER(p_job_name_pattern))
          ORDER BY job_name
          FETCH FIRST l_top_n ROWS ONLY
        )
      ),
      'truncated' VALUE (
        SELECT CASE
                 WHEN COUNT(*) > l_top_n THEN 'true'
                 ELSE 'false'
               END
        FROM USER_SCHEDULER_JOBS
        WHERE (p_job_name_pattern IS NULL OR job_name LIKE UPPER(p_job_name_pattern))
      ),
      'rows' VALUE COALESCE((
        SELECT JSON_ARRAYAGG(
                 JSON_OBJECT(
                   'owner' VALUE SYS_CONTEXT('USERENV','CURRENT_SCHEMA'),
                   'job_name' VALUE job_name,
                   'enabled' VALUE enabled,
                   'state' VALUE state,
                   'job_style' VALUE job_style,
                   'job_type' VALUE job_type,
                   'job_action' VALUE job_action,
                   'program_name' VALUE program_name,
                   'schedule_name' VALUE schedule_name,
                   'job_class' VALUE job_class,
                   'repeat_interval' VALUE repeat_interval,
                   'last_start_date' VALUE TO_CHAR(last_start_date, 'YYYY-MM-DD\"T\"HH24:MI:SS TZH:TZM'),
                   'next_run_date' VALUE TO_CHAR(next_run_date, 'YYYY-MM-DD\"T\"HH24:MI:SS TZH:TZM'),
                   'run_count' VALUE run_count,
                   'failure_count' VALUE failure_count,
                   'retry_count' VALUE retry_count,
                   'max_failures' VALUE max_failures,
                   'max_runs' VALUE max_runs,
                   'auto_drop' VALUE auto_drop,
                   'restartable' VALUE restartable,
                   'logging_level' VALUE logging_level,
                   'stop_on_window_close' VALUE stop_on_window_close
                 )
               RETURNING CLOB)
        FROM (
          SELECT *
          FROM USER_SCHEDULER_JOBS
          WHERE (p_job_name_pattern IS NULL OR job_name LIKE UPPER(p_job_name_pattern))
          ORDER BY job_name
          FETCH FIRST l_top_n ROWS ONLY
        )
      ), TO_CLOB('[]'))
    RETURNING CLOB) INTO l_json
    FROM dual;

    write_log('list_all_jobs', l_start_ts, 'SUCCESS');
    RETURN l_json;
  EXCEPTION
    WHEN OTHERS THEN
      write_log('list_all_jobs', l_start_ts, 'ERROR', SQLERRM);
      RETURN JSON_OBJECT('status' VALUE 'error', 'message' VALUE SQLERRM);
  END list_all_jobs;

  PROCEDURE write_log(
    p_operation_name IN VARCHAR2,
    p_start_ts       IN TIMESTAMP,
    p_status         IN VARCHAR2,
    p_error_message  IN CLOB DEFAULT NULL
  ) IS
    l_duration_ms NUMBER;
    l_delta       INTERVAL DAY TO SECOND;
  BEGIN
    l_delta := SYSTIMESTAMP - CAST(p_start_ts AS TIMESTAMP WITH TIME ZONE);
    l_duration_ms :=
        (EXTRACT(DAY FROM l_delta) * 86400000) +
        (EXTRACT(HOUR FROM l_delta) * 3600000) +
        (EXTRACT(MINUTE FROM l_delta) * 60000) +
        (EXTRACT(SECOND FROM l_delta) * 1000);
    BEGIN
      INSERT INTO SCHED_MONITOR_LOG$(operation_name, duration_ms, status, error_message)
      VALUES (p_operation_name, l_duration_ms, p_status, p_error_message);
    EXCEPTION
      WHEN OTHERS THEN
        NULL;
    END;
  END write_log;

  FUNCTION list_running_jobs(
    p_owner            IN VARCHAR2 DEFAULT NULL,
    p_job_name_pattern IN VARCHAR2 DEFAULT NULL,
    p_top_n            IN NUMBER DEFAULT 200
  ) RETURN CLOB IS
    l_start_ts TIMESTAMP := SYSTIMESTAMP;
    l_json CLOB;
    l_top_n NUMBER := clamp_top_n(p_top_n, 200, 5000);
  BEGIN
    SELECT JSON_OBJECT(
      'summary' VALUE JSON_OBJECT(
        'running_jobs' VALUE COUNT(*)
      ),
      'rows' VALUE COALESCE(
        JSON_ARRAYAGG(
          JSON_OBJECT(
            'owner' VALUE SYS_CONTEXT('USERENV','CURRENT_SCHEMA'),
            'job_name' VALUE job_name,
            'session_id' VALUE session_id,
            'running_instance' VALUE running_instance,
            'elapsed_time' VALUE scheduler_monitoring.format_duration(elapsed_time),
            'cpu_used_seconds' VALUE cpu_used,
            'slave_os_process_id' VALUE slave_os_process_id
          )
        ),
        JSON_ARRAY()
      )
    )
    INTO l_json
    FROM (
      SELECT job_name,
             session_id,
             running_instance,
             EXTRACT(DAY FROM elapsed_time) * 86400 + EXTRACT(HOUR FROM elapsed_time) * 3600 +
             EXTRACT(MINUTE FROM elapsed_time) * 60 + EXTRACT(SECOND FROM elapsed_time) AS elapsed_time,
             EXTRACT(DAY FROM cpu_used) * 86400 + EXTRACT(HOUR FROM cpu_used) * 3600 +
             EXTRACT(MINUTE FROM cpu_used) * 60 + EXTRACT(SECOND FROM cpu_used) AS cpu_used,
             slave_os_process_id
      FROM USER_SCHEDULER_RUNNING_JOBS
      WHERE (p_job_name_pattern IS NULL OR job_name LIKE UPPER(p_job_name_pattern))
      ORDER BY elapsed_time DESC
      FETCH FIRST l_top_n ROWS ONLY
    );

    write_log('list_running_jobs', l_start_ts, 'SUCCESS');
    RETURN l_json;
  EXCEPTION
    WHEN OTHERS THEN
      write_log('list_running_jobs', l_start_ts, 'ERROR', SQLERRM);
      RETURN JSON_OBJECT('status' VALUE 'error', 'message' VALUE SQLERRM);
  END list_running_jobs;

  FUNCTION list_job_history(
    p_start_time       IN VARCHAR2,
    p_end_time         IN VARCHAR2,
    p_owner            IN VARCHAR2 DEFAULT NULL,
    p_job_name_pattern IN VARCHAR2 DEFAULT NULL,
    p_status           IN VARCHAR2 DEFAULT NULL,
    p_top_n            IN NUMBER DEFAULT 1000
  ) RETURN CLOB IS
    l_start_ts_log TIMESTAMP := SYSTIMESTAMP;
    l_json CLOB;
    l_status VARCHAR2(40) := sanitize_status(p_status);
    l_top_n NUMBER := clamp_top_n(p_top_n, 1000, 10000);
    l_from_ts TIMESTAMP WITH TIME ZONE := parse_ts(p_start_time);
    l_to_ts   TIMESTAMP WITH TIME ZONE := parse_ts(p_end_time);
  BEGIN
    IF l_from_ts IS NULL OR l_to_ts IS NULL THEN
      RETURN JSON_OBJECT('status' VALUE 'error', 'message' VALUE 'start_time and end_time are required.');
    END IF;

    SELECT JSON_OBJECT(
      'interval' VALUE JSON_OBJECT(
        'start_time' VALUE TO_CHAR(l_from_ts, 'YYYY-MM-DD"T"HH24:MI:SS TZH:TZM'),
        'end_time' VALUE TO_CHAR(l_to_ts, 'YYYY-MM-DD"T"HH24:MI:SS TZH:TZM')
      ),
      'summary' VALUE JSON_OBJECT(
        'total_runs' VALUE COUNT(*),
        'succeeded_runs' VALUE SUM(CASE WHEN status = 'SUCCEEDED' THEN 1 ELSE 0 END),
        'failed_runs' VALUE SUM(CASE WHEN status = 'FAILED' THEN 1 ELSE 0 END),
        'avg_elapsed_time' VALUE scheduler_monitoring.format_duration(ROUND(AVG(elapsed_seconds), 3)),
        'min_elapsed_time' VALUE scheduler_monitoring.format_duration(MIN(elapsed_seconds)),
        'max_elapsed_time' VALUE scheduler_monitoring.format_duration(MAX(elapsed_seconds)),
        'p95_elapsed_time' VALUE scheduler_monitoring.format_duration(ROUND(PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY elapsed_seconds), 3)),
        'avg_cpu_seconds' VALUE ROUND(AVG(cpu_seconds), 3),
        'min_cpu_seconds' VALUE MIN(cpu_seconds),
        'max_cpu_seconds' VALUE MAX(cpu_seconds),
        'p95_cpu_seconds' VALUE ROUND(PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY cpu_seconds), 3)
      ),
      'rows' VALUE COALESCE(
        JSON_ARRAYAGG(
          JSON_OBJECT(
            'log_id' VALUE log_id,
            'owner' VALUE SYS_CONTEXT('USERENV','CURRENT_SCHEMA'),
            'job_name' VALUE job_name,
            'status' VALUE status,
            'actual_start_time' VALUE TO_CHAR(actual_start_date, 'YYYY-MM-DD"T"HH24:MI:SS TZH:TZM'),
            'run_duration' VALUE run_duration,
            'elapsed_time' VALUE scheduler_monitoring.format_duration(elapsed_seconds),
            'cpu_seconds' VALUE cpu_seconds,
            'error_code' VALUE error#,
            'additional_info' VALUE additional_info,
            'instance_id' VALUE instance_id
          )
        ), JSON_ARRAY()
      )
    )
    INTO l_json
    FROM (
      SELECT rd.log_id,
             rd.job_name,
             rd.status,
             rd.actual_start_date,
             rd.run_duration,
             EXTRACT(DAY FROM rd.run_duration) * 86400 + EXTRACT(HOUR FROM rd.run_duration) * 3600 +
             EXTRACT(MINUTE FROM rd.run_duration) * 60 + EXTRACT(SECOND FROM rd.run_duration) AS elapsed_seconds,
             EXTRACT(DAY FROM rd.cpu_used) * 86400 + EXTRACT(HOUR FROM rd.cpu_used) * 3600 +
             EXTRACT(MINUTE FROM rd.cpu_used) * 60 + EXTRACT(SECOND FROM rd.cpu_used) AS cpu_seconds,
             rd.error#,
             rd.additional_info,
             rd.instance_id
      FROM USER_SCHEDULER_JOB_RUN_DETAILS rd
      WHERE rd.actual_start_date BETWEEN l_from_ts AND l_to_ts
        AND (p_job_name_pattern IS NULL OR rd.job_name LIKE UPPER(p_job_name_pattern))
        AND (l_status IS NULL OR rd.status = l_status)
      ORDER BY rd.actual_start_date DESC
      FETCH FIRST l_top_n ROWS ONLY
    );

    write_log('list_job_history', l_start_ts_log, 'SUCCESS');
    RETURN l_json;
  EXCEPTION
    WHEN OTHERS THEN
      write_log('list_job_history', l_start_ts_log, 'ERROR', SQLERRM);
      RETURN JSON_OBJECT('status' VALUE 'error', 'message' VALUE SQLERRM);
  END list_job_history;

  FUNCTION get_job_details(
    p_owner    IN VARCHAR2,
    p_job_name IN VARCHAR2
  ) RETURN CLOB IS
    l_start_ts TIMESTAMP := SYSTIMESTAMP;
    l_json CLOB;
    l_owner VARCHAR2(128) := UPPER(TRIM(NVL(p_owner, SYS_CONTEXT('USERENV','CURRENT_SCHEMA'))));
    l_job_name VARCHAR2(128) := UPPER(TRIM(p_job_name));
  BEGIN
    SELECT JSON_OBJECT(
      'job_metadata' VALUE (
        SELECT JSON_OBJECT(
          'owner' VALUE SYS_CONTEXT('USERENV','CURRENT_SCHEMA'),
          'job_name' VALUE j.job_name,
          'enabled' VALUE j.enabled,
          'state' VALUE j.state,
          'job_style' VALUE j.job_style,
          'job_type' VALUE j.job_type,
          'job_action' VALUE j.job_action,
          'program_name' VALUE j.program_name,
          'schedule_name' VALUE j.schedule_name,
          'job_class' VALUE j.job_class,
          'logging_level' VALUE j.logging_level,
          'restartable' VALUE j.restartable,
          'auto_drop' VALUE j.auto_drop,
          'max_failures' VALUE j.max_failures,
          'max_runs' VALUE j.max_runs,
          'repeat_interval' VALUE j.repeat_interval,
          'last_start_date' VALUE TO_CHAR(j.last_start_date, 'YYYY-MM-DD"T"HH24:MI:SS TZH:TZM'),
          'next_run_date' VALUE TO_CHAR(j.next_run_date, 'YYYY-MM-DD"T"HH24:MI:SS TZH:TZM'),
          'failure_count' VALUE j.failure_count,
          'credential_name' VALUE j.credential_name
        )
        FROM USER_SCHEDULER_JOBS j
        WHERE j.job_name = l_job_name
      ),
      'job_arguments' VALUE COALESCE((
        SELECT JSON_ARRAYAGG(
          JSON_OBJECT(
            'argument_position' VALUE a.argument_position,
            'argument_name' VALUE a.argument_name,
            'argument_type' VALUE a.argument_type,
            'value' VALUE a.value,
            'out_argument' VALUE a.out_argument
          )
        )
        FROM USER_SCHEDULER_JOB_ARGS a
        WHERE a.job_name = l_job_name
      ), JSON_ARRAY()),
      'recent_runs' VALUE COALESCE((
        SELECT JSON_ARRAYAGG(
          JSON_OBJECT(
            'log_id' VALUE r.log_id,
            'status' VALUE r.status,
            'actual_start_time' VALUE TO_CHAR(r.actual_start_date, 'YYYY-MM-DD"T"HH24:MI:SS TZH:TZM'),
            'run_duration' VALUE r.run_duration,
            'cpu_used' VALUE r.cpu_used,
            'error_code' VALUE r.error#,
            'additional_info' VALUE r.additional_info
          )
        )
        FROM (
          SELECT * FROM USER_SCHEDULER_JOB_RUN_DETAILS
          WHERE job_name = l_job_name
          ORDER BY actual_start_date DESC
          FETCH FIRST 200 ROWS ONLY
        ) r
      ), JSON_ARRAY())
    ) INTO l_json
    FROM dual;

    write_log('get_job_details', l_start_ts, 'SUCCESS');
    RETURN l_json;
  EXCEPTION
    WHEN OTHERS THEN
      write_log('get_job_details', l_start_ts, 'ERROR', SQLERRM);
      RETURN JSON_OBJECT('status' VALUE 'error', 'message' VALUE SQLERRM);
  END get_job_details;

  FUNCTION analyze_cpu_by_job(
    p_start_time       IN VARCHAR2,
    p_end_time         IN VARCHAR2,
    p_owner            IN VARCHAR2 DEFAULT NULL,
    p_job_name_pattern IN VARCHAR2 DEFAULT NULL,
    p_top_n            IN NUMBER DEFAULT 20
  ) RETURN CLOB IS
    l_start_ts TIMESTAMP := SYSTIMESTAMP;
    l_json CLOB;
    l_top_n NUMBER := clamp_top_n(p_top_n, 20, 500);
    l_from_ts TIMESTAMP WITH TIME ZONE := parse_ts(p_start_time);
    l_to_ts   TIMESTAMP WITH TIME ZONE := parse_ts(p_end_time);
  BEGIN
    SELECT JSON_OBJECT(
      'summary' VALUE JSON_OBJECT(
        'total_cpu_seconds' VALUE ROUND(SUM(cpu_seconds), 3),
        'total_elapsed_seconds' VALUE ROUND(SUM(elapsed_seconds), 3)
      ),
      'top_cpu_jobs' VALUE COALESCE(
        JSON_ARRAYAGG(
          JSON_OBJECT(
            'owner' VALUE SYS_CONTEXT('USERENV','CURRENT_SCHEMA'),
            'job_name' VALUE job_name,
            'runs' VALUE run_count,
            'total_cpu_seconds' VALUE total_cpu_seconds,
            'total_elapsed_time' VALUE scheduler_monitoring.format_duration(total_elapsed_seconds),
            'cpu_per_run' VALUE cpu_per_run,
            'cpu_per_minute' VALUE cpu_per_minute,
            'cpu_to_elapsed_ratio' VALUE cpu_elapsed_ratio
          )
        ), JSON_ARRAY()
      )
    )
    INTO l_json
    FROM (
      SELECT job_name,
             COUNT(*) AS run_count,
             ROUND(SUM(cpu_seconds), 3) AS total_cpu_seconds,
             ROUND(SUM(elapsed_seconds), 3) AS total_elapsed_seconds,
             ROUND(SUM(cpu_seconds)/NULLIF(COUNT(*),0), 3) AS cpu_per_run,
             ROUND((SUM(cpu_seconds)/NULLIF(SUM(elapsed_seconds),0))*60, 3) AS cpu_per_minute,
             ROUND(SUM(cpu_seconds)/NULLIF(SUM(elapsed_seconds),0), 4) AS cpu_elapsed_ratio,
             SUM(cpu_seconds) AS cpu_seconds,
             SUM(elapsed_seconds) AS elapsed_seconds
      FROM (
        SELECT rd.job_name,
               EXTRACT(DAY FROM rd.cpu_used) * 86400 + EXTRACT(HOUR FROM rd.cpu_used) * 3600 +
               EXTRACT(MINUTE FROM rd.cpu_used) * 60 + EXTRACT(SECOND FROM rd.cpu_used) AS cpu_seconds,
               EXTRACT(DAY FROM rd.run_duration) * 86400 + EXTRACT(HOUR FROM rd.run_duration) * 3600 +
               EXTRACT(MINUTE FROM rd.run_duration) * 60 + EXTRACT(SECOND FROM rd.run_duration) AS elapsed_seconds
        FROM USER_SCHEDULER_JOB_RUN_DETAILS rd
        WHERE rd.actual_start_date BETWEEN l_from_ts AND l_to_ts
          AND (p_job_name_pattern IS NULL OR rd.job_name LIKE UPPER(p_job_name_pattern))
      )
      GROUP BY job_name
      ORDER BY total_cpu_seconds DESC
      FETCH FIRST l_top_n ROWS ONLY
    );

    write_log('analyze_cpu_by_job', l_start_ts, 'SUCCESS');
    RETURN l_json;
  EXCEPTION
    WHEN OTHERS THEN
      write_log('analyze_cpu_by_job', l_start_ts, 'ERROR', SQLERRM);
      RETURN JSON_OBJECT('status' VALUE 'error', 'message' VALUE SQLERRM);
  END analyze_cpu_by_job;

  FUNCTION analyze_load_by_job(
    p_start_time       IN VARCHAR2,
    p_end_time         IN VARCHAR2,
    p_owner            IN VARCHAR2 DEFAULT NULL,
    p_job_name_pattern IN VARCHAR2 DEFAULT NULL,
    p_granularity      IN VARCHAR2 DEFAULT 'HOUR'
  ) RETURN CLOB IS
    l_start_ts TIMESTAMP := SYSTIMESTAMP;
    l_json CLOB;
    l_from_ts TIMESTAMP WITH TIME ZONE := parse_ts(p_start_time);
    l_to_ts   TIMESTAMP WITH TIME ZONE := parse_ts(p_end_time);
    l_gran VARCHAR2(20) := sanitize_granularity(p_granularity);
  BEGIN
    SELECT JSON_OBJECT(
      'correlation_mode' VALUE 'inferred_time_window',
      'confidence' VALUE 'medium',
      'rows' VALUE COALESCE(
        JSON_ARRAYAGG(
          JSON_OBJECT(
            'bucket_time' VALUE bucket_time,
            'runs' VALUE runs,
            'failed_runs' VALUE failed_runs,
            'avg_cpu_seconds' VALUE avg_cpu_seconds,
            'avg_elapsed_time' VALUE scheduler_monitoring.format_duration(avg_elapsed_seconds),
            'cpu_load_proxy' VALUE cpu_load_proxy
          )
        ), JSON_ARRAY()
      )
    )
    INTO l_json
    FROM (
      SELECT TO_CHAR(
               CASE l_gran
                 WHEN 'DAY' THEN CAST(TRUNC(CAST(rd.actual_start_date AS DATE)) AS TIMESTAMP)
                 WHEN 'HOUR' THEN CAST(TRUNC(CAST(rd.actual_start_date AS DATE), 'HH24') AS TIMESTAMP)
                 ELSE CAST(TRUNC(CAST(rd.actual_start_date AS DATE), 'MI') AS TIMESTAMP)
               END,
               'YYYY-MM-DD HH24:MI:SS'
             ) AS bucket_time,
             COUNT(*) AS runs,
             SUM(CASE WHEN rd.status = 'FAILED' THEN 1 ELSE 0 END) AS failed_runs,
             ROUND(AVG(EXTRACT(DAY FROM rd.cpu_used) * 86400 + EXTRACT(HOUR FROM rd.cpu_used) * 3600 +
                   EXTRACT(MINUTE FROM rd.cpu_used) * 60 + EXTRACT(SECOND FROM rd.cpu_used)), 3) AS avg_cpu_seconds,
             ROUND(AVG(EXTRACT(DAY FROM rd.run_duration) * 86400 + EXTRACT(HOUR FROM rd.run_duration) * 3600 +
                   EXTRACT(MINUTE FROM rd.run_duration) * 60 + EXTRACT(SECOND FROM rd.run_duration)), 3) AS avg_elapsed_seconds,
             ROUND(AVG((EXTRACT(DAY FROM rd.cpu_used) * 86400 + EXTRACT(HOUR FROM rd.cpu_used) * 3600 +
                   EXTRACT(MINUTE FROM rd.cpu_used) * 60 + EXTRACT(SECOND FROM rd.cpu_used)) /
                  NULLIF((EXTRACT(DAY FROM rd.run_duration) * 86400 + EXTRACT(HOUR FROM rd.run_duration) * 3600 +
                   EXTRACT(MINUTE FROM rd.run_duration) * 60 + EXTRACT(SECOND FROM rd.run_duration)), 0)), 4) AS cpu_load_proxy
      FROM USER_SCHEDULER_JOB_RUN_DETAILS rd
      WHERE rd.actual_start_date BETWEEN l_from_ts AND l_to_ts
        AND (p_job_name_pattern IS NULL OR rd.job_name LIKE UPPER(p_job_name_pattern))
      GROUP BY CASE l_gran
                 WHEN 'DAY' THEN TRUNC(CAST(rd.actual_start_date AS DATE))
                 WHEN 'HOUR' THEN TRUNC(CAST(rd.actual_start_date AS DATE), 'HH24')
                 ELSE TRUNC(CAST(rd.actual_start_date AS DATE), 'MI')
               END
      ORDER BY bucket_time
    );

    write_log('analyze_load_by_job', l_start_ts, 'SUCCESS');
    RETURN l_json;
  EXCEPTION
    WHEN OTHERS THEN
      write_log('analyze_load_by_job', l_start_ts, 'ERROR', SQLERRM);
      RETURN JSON_OBJECT('status' VALUE 'error', 'message' VALUE SQLERRM);
  END analyze_load_by_job;

  FUNCTION compare_jobs(
    p_start_time IN VARCHAR2,
    p_end_time   IN VARCHAR2,
    p_owner      IN VARCHAR2,
    p_job_a      IN VARCHAR2,
    p_job_b      IN VARCHAR2
  ) RETURN CLOB IS
    l_start_ts TIMESTAMP := SYSTIMESTAMP;
    l_json CLOB;
    l_job_a VARCHAR2(128) := UPPER(TRIM(p_job_a));
    l_job_b VARCHAR2(128) := UPPER(TRIM(p_job_b));
    l_from_ts TIMESTAMP WITH TIME ZONE := parse_ts(p_start_time);
    l_to_ts   TIMESTAMP WITH TIME ZONE := parse_ts(p_end_time);
  BEGIN
    SELECT JSON_OBJECT(
      'job_a' VALUE (
        SELECT JSON_OBJECT(
          'job_name' VALUE l_job_a,
          'runs' VALUE COUNT(*),
          'failed_runs' VALUE SUM(CASE WHEN status='FAILED' THEN 1 ELSE 0 END),
          'avg_elapsed_time' VALUE scheduler_monitoring.format_duration(ROUND(AVG(elapsed_seconds), 3)),
          'avg_cpu_seconds' VALUE ROUND(AVG(cpu_seconds), 3),
          'p95_elapsed_time' VALUE scheduler_monitoring.format_duration(ROUND(PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY elapsed_seconds), 3))
        )
        FROM (
          SELECT status,
                 EXTRACT(DAY FROM run_duration) * 86400 + EXTRACT(HOUR FROM run_duration) * 3600 +
                 EXTRACT(MINUTE FROM run_duration) * 60 + EXTRACT(SECOND FROM run_duration) AS elapsed_seconds,
                 EXTRACT(DAY FROM cpu_used) * 86400 + EXTRACT(HOUR FROM cpu_used) * 3600 +
                 EXTRACT(MINUTE FROM cpu_used) * 60 + EXTRACT(SECOND FROM cpu_used) AS cpu_seconds
          FROM USER_SCHEDULER_JOB_RUN_DETAILS
          WHERE job_name = l_job_a
            AND actual_start_date BETWEEN l_from_ts AND l_to_ts
        )
      ),
      'job_b' VALUE (
        SELECT JSON_OBJECT(
          'job_name' VALUE l_job_b,
          'runs' VALUE COUNT(*),
          'failed_runs' VALUE SUM(CASE WHEN status='FAILED' THEN 1 ELSE 0 END),
          'avg_elapsed_time' VALUE scheduler_monitoring.format_duration(ROUND(AVG(elapsed_seconds), 3)),
          'avg_cpu_seconds' VALUE ROUND(AVG(cpu_seconds), 3),
          'p95_elapsed_time' VALUE scheduler_monitoring.format_duration(ROUND(PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY elapsed_seconds), 3))
        )
        FROM (
          SELECT status,
                 EXTRACT(DAY FROM run_duration) * 86400 + EXTRACT(HOUR FROM run_duration) * 3600 +
                 EXTRACT(MINUTE FROM run_duration) * 60 + EXTRACT(SECOND FROM run_duration) AS elapsed_seconds,
                 EXTRACT(DAY FROM cpu_used) * 86400 + EXTRACT(HOUR FROM cpu_used) * 3600 +
                 EXTRACT(MINUTE FROM cpu_used) * 60 + EXTRACT(SECOND FROM cpu_used) AS cpu_seconds
          FROM USER_SCHEDULER_JOB_RUN_DETAILS
          WHERE job_name = l_job_b
            AND actual_start_date BETWEEN l_from_ts AND l_to_ts
        )
      )
    ) INTO l_json
    FROM dual;

    write_log('compare_jobs', l_start_ts, 'SUCCESS');
    RETURN l_json;
  EXCEPTION
    WHEN OTHERS THEN
      write_log('compare_jobs', l_start_ts, 'ERROR', SQLERRM);
      RETURN JSON_OBJECT('status' VALUE 'error', 'message' VALUE SQLERRM);
  END compare_jobs;

  FUNCTION identify_hotspots(
    p_start_time  IN VARCHAR2,
    p_end_time    IN VARCHAR2,
    p_top_n       IN NUMBER DEFAULT 20,
    p_min_elapsed IN NUMBER DEFAULT 0,
    p_min_cpu     IN NUMBER DEFAULT 0
  ) RETURN CLOB IS
    l_start_ts TIMESTAMP := SYSTIMESTAMP;
    l_json CLOB;
    l_top_n NUMBER := clamp_top_n(p_top_n, 20, 500);
    l_from_ts TIMESTAMP WITH TIME ZONE := parse_ts(p_start_time);
    l_to_ts   TIMESTAMP WITH TIME ZONE := parse_ts(p_end_time);
  BEGIN
    SELECT JSON_OBJECT(
      'rows' VALUE COALESCE(
        JSON_ARRAYAGG(
          JSON_OBJECT(
            'owner' VALUE SYS_CONTEXT('USERENV','CURRENT_SCHEMA'),
            'job_name' VALUE job_name,
            'runs' VALUE runs,
            'total_cpu_seconds' VALUE total_cpu_seconds,
            'total_elapsed_time' VALUE scheduler_monitoring.format_duration(total_elapsed_seconds),
            'avg_cpu_to_elapsed_ratio' VALUE cpu_elapsed_ratio,
            'hotspot_reason' VALUE hotspot_reason
          )
        ), JSON_ARRAY()
      )
    ) INTO l_json
    FROM (
      SELECT job_name,
             COUNT(*) runs,
             ROUND(SUM(cpu_seconds), 3) total_cpu_seconds,
             ROUND(SUM(elapsed_seconds), 3) total_elapsed_seconds,
             ROUND(AVG(cpu_seconds/NULLIF(elapsed_seconds,0)), 4) cpu_elapsed_ratio,
             CASE
               WHEN SUM(cpu_seconds) >= p_min_cpu AND SUM(elapsed_seconds) >= p_min_elapsed THEN 'high_cpu_and_long_runtime'
               WHEN SUM(cpu_seconds) >= p_min_cpu THEN 'high_cpu'
               ELSE 'long_runtime'
             END hotspot_reason
      FROM (
        SELECT job_name,
               EXTRACT(DAY FROM cpu_used) * 86400 + EXTRACT(HOUR FROM cpu_used) * 3600 +
               EXTRACT(MINUTE FROM cpu_used) * 60 + EXTRACT(SECOND FROM cpu_used) AS cpu_seconds,
               EXTRACT(DAY FROM run_duration) * 86400 + EXTRACT(HOUR FROM run_duration) * 3600 +
               EXTRACT(MINUTE FROM run_duration) * 60 + EXTRACT(SECOND FROM run_duration) AS elapsed_seconds
        FROM USER_SCHEDULER_JOB_RUN_DETAILS
        WHERE actual_start_date BETWEEN l_from_ts AND l_to_ts
      )
      GROUP BY job_name
      HAVING SUM(elapsed_seconds) >= NVL(p_min_elapsed, 0)
         OR SUM(cpu_seconds) >= NVL(p_min_cpu, 0)
      ORDER BY total_cpu_seconds DESC, total_elapsed_seconds DESC
      FETCH FIRST l_top_n ROWS ONLY
    );

    write_log('identify_hotspots', l_start_ts, 'SUCCESS');
    RETURN l_json;
  EXCEPTION
    WHEN OTHERS THEN
      write_log('identify_hotspots', l_start_ts, 'ERROR', SQLERRM);
      RETURN JSON_OBJECT('status' VALUE 'error', 'message' VALUE SQLERRM);
  END identify_hotspots;

  FUNCTION detect_failures(
    p_start_time       IN VARCHAR2,
    p_end_time         IN VARCHAR2,
    p_owner            IN VARCHAR2 DEFAULT NULL,
    p_job_name_pattern IN VARCHAR2 DEFAULT NULL,
    p_top_n            IN NUMBER DEFAULT 100
  ) RETURN CLOB IS
    l_start_ts TIMESTAMP := SYSTIMESTAMP;
    l_json CLOB;
    l_top_n NUMBER := clamp_top_n(p_top_n, 100, 2000);
    l_from_ts TIMESTAMP WITH TIME ZONE := parse_ts(p_start_time);
    l_to_ts   TIMESTAMP WITH TIME ZONE := parse_ts(p_end_time);
  BEGIN
    SELECT JSON_OBJECT(
      'summary' VALUE JSON_OBJECT(
        'failed_runs' VALUE COUNT(*),
        'distinct_jobs_failed' VALUE COUNT(DISTINCT job_name)
      ),
      'top_failures' VALUE COALESCE(
        JSON_ARRAYAGG(
          JSON_OBJECT(
            'owner' VALUE SYS_CONTEXT('USERENV','CURRENT_SCHEMA'),
            'job_name' VALUE job_name,
            'failures' VALUE failures,
            'last_failure_time' VALUE TO_CHAR(last_failure_time, 'YYYY-MM-DD"T"HH24:MI:SS TZH:TZM'),
            'common_error_code' VALUE common_error_code,
            'common_error_message' VALUE common_error_message
          )
        ), JSON_ARRAY()
      )
    )
    INTO l_json
    FROM (
      SELECT job_name,
             COUNT(*) failures,
             MAX(actual_start_date) last_failure_time,
             MIN(error#) KEEP (DENSE_RANK FIRST ORDER BY COUNT(*) DESC) common_error_code,
             MIN(additional_info) KEEP (DENSE_RANK FIRST ORDER BY COUNT(*) DESC) common_error_message
      FROM USER_SCHEDULER_JOB_RUN_DETAILS
      WHERE actual_start_date BETWEEN l_from_ts AND l_to_ts
        AND status = 'FAILED'
        AND (p_job_name_pattern IS NULL OR job_name LIKE UPPER(p_job_name_pattern))
      GROUP BY job_name
      ORDER BY failures DESC, last_failure_time DESC
      FETCH FIRST l_top_n ROWS ONLY
    );

    write_log('detect_failures', l_start_ts, 'SUCCESS');
    RETURN l_json;
  EXCEPTION
    WHEN OTHERS THEN
      write_log('detect_failures', l_start_ts, 'ERROR', SQLERRM);
      RETURN JSON_OBJECT('status' VALUE 'error', 'message' VALUE SQLERRM);
  END detect_failures;

  FUNCTION summarize_scheduler_health(
    p_start_time  IN VARCHAR2,
    p_end_time    IN VARCHAR2,
    p_owner       IN VARCHAR2 DEFAULT NULL,
    p_top_n       IN NUMBER DEFAULT 10
  ) RETURN CLOB IS
    l_start_ts TIMESTAMP := SYSTIMESTAMP;
    l_json CLOB;
    l_top_n NUMBER := clamp_top_n(p_top_n, 10, 100);
    l_from_ts TIMESTAMP WITH TIME ZONE := parse_ts(p_start_time);
    l_to_ts   TIMESTAMP WITH TIME ZONE := parse_ts(p_end_time);
  BEGIN
    SELECT JSON_OBJECT(
      'executive_summary' VALUE JSON_OBJECT(
        'total_jobs' VALUE (SELECT COUNT(*) FROM USER_SCHEDULER_JOBS j),
        'running_jobs' VALUE (SELECT COUNT(*) FROM USER_SCHEDULER_RUNNING_JOBS r),
        'disabled_jobs' VALUE (SELECT COUNT(*) FROM USER_SCHEDULER_JOBS j WHERE j.enabled = 'FALSE'),
        'broken_jobs' VALUE (SELECT COUNT(*) FROM USER_SCHEDULER_JOBS j WHERE j.state = 'BROKEN'),
        'jobs_executed_in_interval' VALUE (SELECT COUNT(*) FROM USER_SCHEDULER_JOB_RUN_DETAILS d WHERE d.actual_start_date BETWEEN l_from_ts AND l_to_ts),
        'failed_runs_in_interval' VALUE (SELECT COUNT(*) FROM USER_SCHEDULER_JOB_RUN_DETAILS d WHERE d.actual_start_date BETWEEN l_from_ts AND l_to_ts AND d.status = 'FAILED')
      ),
      'top_10_cpu_jobs' VALUE (
        SELECT COALESCE(JSON_ARRAYAGG(
          JSON_OBJECT('owner' VALUE SYS_CONTEXT('USERENV','CURRENT_SCHEMA'),'job_name' VALUE job_name,'total_cpu_seconds' VALUE total_cpu_seconds)
        ), JSON_ARRAY())
        FROM (
          SELECT job_name,
                 ROUND(SUM(EXTRACT(DAY FROM cpu_used) * 86400 + EXTRACT(HOUR FROM cpu_used) * 3600 +
                       EXTRACT(MINUTE FROM cpu_used) * 60 + EXTRACT(SECOND FROM cpu_used)), 3) total_cpu_seconds
          FROM USER_SCHEDULER_JOB_RUN_DETAILS
          WHERE actual_start_date BETWEEN l_from_ts AND l_to_ts
          GROUP BY job_name
          ORDER BY total_cpu_seconds DESC
          FETCH FIRST l_top_n ROWS ONLY
        )
      ),
      'top_10_failure_jobs' VALUE (
        SELECT COALESCE(JSON_ARRAYAGG(
          JSON_OBJECT('owner' VALUE SYS_CONTEXT('USERENV','CURRENT_SCHEMA'),'job_name' VALUE job_name,'failed_runs' VALUE failed_runs)
        ), JSON_ARRAY())
        FROM (
          SELECT job_name, COUNT(*) failed_runs
          FROM USER_SCHEDULER_JOB_RUN_DETAILS
          WHERE actual_start_date BETWEEN l_from_ts AND l_to_ts
            AND status = 'FAILED'
          GROUP BY job_name
          ORDER BY failed_runs DESC
          FETCH FIRST l_top_n ROWS ONLY
        )
      ),
      'recommendations' VALUE JSON_ARRAY(
        'Reschedule jobs with repeated failures to non-peak windows.',
        'Stagger top CPU jobs to reduce concurrency hotspots.',
        'Review jobs with high CPU-to-elapsed ratio for SQL optimization.',
        'Increase instrumentation (module/action/client_identifier) for weakly correlated runs.'
      )
    ) INTO l_json
    FROM dual;

    write_log('summarize_scheduler_health', l_start_ts, 'SUCCESS');
    RETURN l_json;
  EXCEPTION
    WHEN OTHERS THEN
      write_log('summarize_scheduler_health', l_start_ts, 'ERROR', SQLERRM);
      RETURN JSON_OBJECT('status' VALUE 'error', 'message' VALUE SQLERRM);
  END summarize_scheduler_health;

  FUNCTION generate_charts(
    p_start_time       IN VARCHAR2,
    p_end_time         IN VARCHAR2,
    p_owner            IN VARCHAR2 DEFAULT NULL,
    p_job_name_pattern IN VARCHAR2 DEFAULT NULL,
    p_granularity      IN VARCHAR2 DEFAULT 'HOUR',
    p_top_n            IN NUMBER DEFAULT 10
  ) RETURN CLOB IS
    l_start_ts TIMESTAMP := SYSTIMESTAMP;
    l_json CLOB;
    l_gran VARCHAR2(20) := sanitize_granularity(p_granularity);
    l_top_n NUMBER := clamp_top_n(p_top_n, 10, 200);
    l_from_ts TIMESTAMP WITH TIME ZONE := parse_ts(p_start_time);
    l_to_ts   TIMESTAMP WITH TIME ZONE := parse_ts(p_end_time);
  BEGIN
    SELECT JSON_OBJECT(
      'chart_specs' VALUE JSON_ARRAY(
        JSON_OBJECT('chart_id' VALUE 'cpu_usage_trend','type' VALUE 'line','x' VALUE 'bucket_time','y' VALUE 'avg_cpu_seconds'),
        JSON_OBJECT('chart_id' VALUE 'load_trend','type' VALUE 'line','x' VALUE 'bucket_time','y' VALUE 'runs'),
        JSON_OBJECT('chart_id' VALUE 'top_cpu_jobs','type' VALUE 'bar','x' VALUE 'job_name','y' VALUE 'total_cpu_seconds'),
        JSON_OBJECT('chart_id' VALUE 'top_longest_jobs','type' VALUE 'bar','x' VALUE 'job_name','y' VALUE 'total_elapsed_seconds'),
        JSON_OBJECT('chart_id' VALUE 'failure_by_job','type' VALUE 'bar','x' VALUE 'job_name','y' VALUE 'failed_runs'),
        JSON_OBJECT('chart_id' VALUE 'elapsed_vs_cpu','type' VALUE 'scatter','x' VALUE 'elapsed_seconds','y' VALUE 'cpu_seconds')
      ),
      'datasets' VALUE JSON_OBJECT(
        'cpu_usage_trend' VALUE (
          SELECT COALESCE(JSON_ARRAYAGG(
            JSON_OBJECT('bucket_time' VALUE bucket_time,'avg_cpu_seconds' VALUE avg_cpu_seconds)
          ), JSON_ARRAY())
          FROM (
            SELECT TO_CHAR(
                     CASE l_gran
                       WHEN 'DAY' THEN TRUNC(CAST(actual_start_date AS DATE))
                       WHEN 'HOUR' THEN TRUNC(CAST(actual_start_date AS DATE), 'HH24')
                       ELSE TRUNC(CAST(actual_start_date AS DATE), 'MI')
                     END,
                     'YYYY-MM-DD HH24:MI:SS'
                   ) bucket_time,
                   ROUND(AVG(EXTRACT(DAY FROM cpu_used) * 86400 + EXTRACT(HOUR FROM cpu_used) * 3600 +
                         EXTRACT(MINUTE FROM cpu_used) * 60 + EXTRACT(SECOND FROM cpu_used)), 3) avg_cpu_seconds
            FROM USER_SCHEDULER_JOB_RUN_DETAILS
            WHERE actual_start_date BETWEEN l_from_ts AND l_to_ts
              AND (p_job_name_pattern IS NULL OR job_name LIKE UPPER(p_job_name_pattern))
            GROUP BY CASE l_gran
                       WHEN 'DAY' THEN TRUNC(CAST(actual_start_date AS DATE))
                       WHEN 'HOUR' THEN TRUNC(CAST(actual_start_date AS DATE), 'HH24')
                       ELSE TRUNC(CAST(actual_start_date AS DATE), 'MI')
                     END
            ORDER BY bucket_time
          )
        ),
        'top_cpu_jobs' VALUE (
          SELECT COALESCE(JSON_ARRAYAGG(
            JSON_OBJECT('job_name' VALUE job_name,'total_cpu_seconds' VALUE total_cpu_seconds)
          ), JSON_ARRAY())
          FROM (
            SELECT job_name,
                   ROUND(SUM(EXTRACT(DAY FROM cpu_used) * 86400 + EXTRACT(HOUR FROM cpu_used) * 3600 +
                         EXTRACT(MINUTE FROM cpu_used) * 60 + EXTRACT(SECOND FROM cpu_used)), 3) total_cpu_seconds
            FROM USER_SCHEDULER_JOB_RUN_DETAILS
            WHERE actual_start_date BETWEEN l_from_ts AND l_to_ts
              AND (p_job_name_pattern IS NULL OR job_name LIKE UPPER(p_job_name_pattern))
            GROUP BY job_name
            ORDER BY total_cpu_seconds DESC
            FETCH FIRST l_top_n ROWS ONLY
          )
        )
      )
    ) INTO l_json
    FROM dual;

    write_log('generate_charts', l_start_ts, 'SUCCESS');
    RETURN l_json;
  EXCEPTION
    WHEN OTHERS THEN
      write_log('generate_charts', l_start_ts, 'ERROR', SQLERRM);
      RETURN JSON_OBJECT('status' VALUE 'error', 'message' VALUE SQLERRM);
  END generate_charts;

  FUNCTION export_tables(
    p_start_time       IN VARCHAR2,
    p_end_time         IN VARCHAR2,
    p_owner            IN VARCHAR2 DEFAULT NULL,
    p_job_name_pattern IN VARCHAR2 DEFAULT NULL,
    p_top_n            IN NUMBER DEFAULT 500
  ) RETURN CLOB IS
    l_start_ts TIMESTAMP := SYSTIMESTAMP;
    l_json CLOB;
    l_owner VARCHAR2(128) := UPPER(TRIM(p_owner));
    l_top_n NUMBER := clamp_top_n(p_top_n, 500, 5000);
    l_from_ts TIMESTAMP WITH TIME ZONE := parse_ts(p_start_time);
    l_to_ts   TIMESTAMP WITH TIME ZONE := parse_ts(p_end_time);
  BEGIN
    SELECT JSON_OBJECT(
      'all_jobs_table' VALUE list_all_jobs(p_job_name_pattern, LEAST(l_top_n, 10000)),
      'running_jobs_table' VALUE list_running_jobs(l_owner, p_job_name_pattern, l_top_n),
      'history_table' VALUE list_job_history(p_start_time, p_end_time, l_owner, p_job_name_pattern, NULL, l_top_n),
      'cpu_table' VALUE analyze_cpu_by_job(p_start_time, p_end_time, l_owner, p_job_name_pattern, LEAST(l_top_n, 1000)),
      'failure_table' VALUE detect_failures(p_start_time, p_end_time, l_owner, p_job_name_pattern, LEAST(l_top_n, 1000))
    ) INTO l_json
    FROM dual;

    write_log('export_tables', l_start_ts, 'SUCCESS');
    RETURN l_json;
  EXCEPTION
    WHEN OTHERS THEN
      write_log('export_tables', l_start_ts, 'ERROR', SQLERRM);
      RETURN JSON_OBJECT('status' VALUE 'error', 'message' VALUE SQLERRM);
  END export_tables;
END scheduler_monitoring;
/

CREATE OR REPLACE PACKAGE select_ai_scheduler_monitor AS
  FUNCTION get_database_current_time RETURN CLOB;

  FUNCTION list_all_jobs(
    job_name_pattern VARCHAR2 DEFAULT NULL,
    top_n            NUMBER DEFAULT 1000
  ) RETURN CLOB;

  FUNCTION list_running_jobs(
    owner_filter      VARCHAR2 DEFAULT NULL,
    job_name_pattern  VARCHAR2 DEFAULT NULL,
    top_n             NUMBER DEFAULT 200
  ) RETURN CLOB;

  FUNCTION list_job_history(
    start_time        VARCHAR2,
    end_time          VARCHAR2,
    owner_filter      VARCHAR2 DEFAULT NULL,
    job_name_pattern  VARCHAR2 DEFAULT NULL,
    status_filter     VARCHAR2 DEFAULT NULL,
    top_n             NUMBER DEFAULT 1000
  ) RETURN CLOB;

  FUNCTION get_job_details(
    owner_name VARCHAR2,
    job_name   VARCHAR2
  ) RETURN CLOB;

  FUNCTION analyze_cpu_by_job(
    start_time        VARCHAR2,
    end_time          VARCHAR2,
    owner_filter      VARCHAR2 DEFAULT NULL,
    job_name_pattern  VARCHAR2 DEFAULT NULL,
    top_n             NUMBER DEFAULT 20
  ) RETURN CLOB;

  FUNCTION analyze_load_by_job(
    start_time        VARCHAR2,
    end_time          VARCHAR2,
    owner_filter      VARCHAR2 DEFAULT NULL,
    job_name_pattern  VARCHAR2 DEFAULT NULL,
    granularity       VARCHAR2 DEFAULT 'HOUR'
  ) RETURN CLOB;

  FUNCTION compare_jobs(
    start_time VARCHAR2,
    end_time   VARCHAR2,
    owner_name VARCHAR2,
    job_a      VARCHAR2,
    job_b      VARCHAR2
  ) RETURN CLOB;

  FUNCTION identify_hotspots(
    start_time  VARCHAR2,
    end_time    VARCHAR2,
    top_n       NUMBER DEFAULT 20,
    min_elapsed NUMBER DEFAULT 0,
    min_cpu     NUMBER DEFAULT 0
  ) RETURN CLOB;

  FUNCTION detect_failures(
    start_time       VARCHAR2,
    end_time         VARCHAR2,
    owner_filter     VARCHAR2 DEFAULT NULL,
    job_name_pattern VARCHAR2 DEFAULT NULL,
    top_n            NUMBER DEFAULT 100
  ) RETURN CLOB;

  FUNCTION summarize_scheduler_health(
    start_time    VARCHAR2,
    end_time      VARCHAR2,
    owner_filter  VARCHAR2 DEFAULT NULL,
    top_n         NUMBER DEFAULT 10
  ) RETURN CLOB;

  FUNCTION generate_charts(
    start_time        VARCHAR2,
    end_time          VARCHAR2,
    owner_filter      VARCHAR2 DEFAULT NULL,
    job_name_pattern  VARCHAR2 DEFAULT NULL,
    granularity       VARCHAR2 DEFAULT 'HOUR',
    top_n             NUMBER DEFAULT 10
  ) RETURN CLOB;

  FUNCTION export_tables(
    start_time        VARCHAR2,
    end_time          VARCHAR2,
    owner_filter      VARCHAR2 DEFAULT NULL,
    job_name_pattern  VARCHAR2 DEFAULT NULL,
    top_n             NUMBER DEFAULT 500
  ) RETURN CLOB;
END select_ai_scheduler_monitor;
/

CREATE OR REPLACE PACKAGE BODY select_ai_scheduler_monitor AS
  FUNCTION get_database_current_time RETURN CLOB IS
  BEGIN
    RETURN scheduler_monitoring.get_database_current_time;
  END get_database_current_time;

  FUNCTION list_all_jobs(job_name_pattern VARCHAR2 DEFAULT NULL, top_n NUMBER DEFAULT 1000) RETURN CLOB IS
  BEGIN
    RETURN scheduler_monitoring.list_all_jobs(job_name_pattern, top_n);
  END list_all_jobs;

  FUNCTION list_running_jobs(owner_filter VARCHAR2 DEFAULT NULL, job_name_pattern VARCHAR2 DEFAULT NULL, top_n NUMBER DEFAULT 200) RETURN CLOB IS
  BEGIN
    RETURN scheduler_monitoring.list_running_jobs(owner_filter, job_name_pattern, top_n);
  END list_running_jobs;

  FUNCTION list_job_history(start_time VARCHAR2, end_time VARCHAR2, owner_filter VARCHAR2 DEFAULT NULL, job_name_pattern VARCHAR2 DEFAULT NULL, status_filter VARCHAR2 DEFAULT NULL, top_n NUMBER DEFAULT 1000) RETURN CLOB IS
  BEGIN
    RETURN scheduler_monitoring.list_job_history(start_time, end_time, owner_filter, job_name_pattern, status_filter, top_n);
  END list_job_history;

  FUNCTION get_job_details(owner_name VARCHAR2, job_name VARCHAR2) RETURN CLOB IS
  BEGIN
    RETURN scheduler_monitoring.get_job_details(owner_name, job_name);
  END get_job_details;

  FUNCTION analyze_cpu_by_job(start_time VARCHAR2, end_time VARCHAR2, owner_filter VARCHAR2 DEFAULT NULL, job_name_pattern VARCHAR2 DEFAULT NULL, top_n NUMBER DEFAULT 20) RETURN CLOB IS
  BEGIN
    RETURN scheduler_monitoring.analyze_cpu_by_job(start_time, end_time, owner_filter, job_name_pattern, top_n);
  END analyze_cpu_by_job;

  FUNCTION analyze_load_by_job(start_time VARCHAR2, end_time VARCHAR2, owner_filter VARCHAR2 DEFAULT NULL, job_name_pattern VARCHAR2 DEFAULT NULL, granularity VARCHAR2 DEFAULT 'HOUR') RETURN CLOB IS
  BEGIN
    RETURN scheduler_monitoring.analyze_load_by_job(start_time, end_time, owner_filter, job_name_pattern, granularity);
  END analyze_load_by_job;

  FUNCTION compare_jobs(start_time VARCHAR2, end_time VARCHAR2, owner_name VARCHAR2, job_a VARCHAR2, job_b VARCHAR2) RETURN CLOB IS
  BEGIN
    RETURN scheduler_monitoring.compare_jobs(start_time, end_time, owner_name, job_a, job_b);
  END compare_jobs;

  FUNCTION identify_hotspots(start_time VARCHAR2, end_time VARCHAR2, top_n NUMBER DEFAULT 20, min_elapsed NUMBER DEFAULT 0, min_cpu NUMBER DEFAULT 0) RETURN CLOB IS
  BEGIN
    RETURN scheduler_monitoring.identify_hotspots(start_time, end_time, top_n, min_elapsed, min_cpu);
  END identify_hotspots;

  FUNCTION detect_failures(start_time VARCHAR2, end_time VARCHAR2, owner_filter VARCHAR2 DEFAULT NULL, job_name_pattern VARCHAR2 DEFAULT NULL, top_n NUMBER DEFAULT 100) RETURN CLOB IS
  BEGIN
    RETURN scheduler_monitoring.detect_failures(start_time, end_time, owner_filter, job_name_pattern, top_n);
  END detect_failures;

  FUNCTION summarize_scheduler_health(start_time VARCHAR2, end_time VARCHAR2, owner_filter VARCHAR2 DEFAULT NULL, top_n NUMBER DEFAULT 10) RETURN CLOB IS
  BEGIN
    RETURN scheduler_monitoring.summarize_scheduler_health(start_time, end_time, owner_filter, top_n);
  END summarize_scheduler_health;

  FUNCTION generate_charts(start_time VARCHAR2, end_time VARCHAR2, owner_filter VARCHAR2 DEFAULT NULL, job_name_pattern VARCHAR2 DEFAULT NULL, granularity VARCHAR2 DEFAULT 'HOUR', top_n NUMBER DEFAULT 10) RETURN CLOB IS
  BEGIN
    RETURN scheduler_monitoring.generate_charts(start_time, end_time, owner_filter, job_name_pattern, granularity, top_n);
  END generate_charts;

  FUNCTION export_tables(start_time VARCHAR2, end_time VARCHAR2, owner_filter VARCHAR2 DEFAULT NULL, job_name_pattern VARCHAR2 DEFAULT NULL, top_n NUMBER DEFAULT 500) RETURN CLOB IS
  BEGIN
    RETURN scheduler_monitoring.export_tables(start_time, end_time, owner_filter, job_name_pattern, top_n);
  END export_tables;
END select_ai_scheduler_monitor;
/

CREATE OR REPLACE PROCEDURE initialize_scheduler_tools
IS
  PROCEDURE drop_tool_if_exists(p_tool_name IN VARCHAR2) IS
    l_tool_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO l_tool_count
    FROM USER_AI_AGENT_TOOLS
    WHERE TOOL_NAME = p_tool_name;

    IF l_tool_count > 0 THEN
      DBMS_CLOUD_AI_AGENT.DROP_TOOL(p_tool_name);
    END IF;
  END drop_tool_if_exists;
BEGIN
  drop_tool_if_exists('GET_DATABASE_CURRENT_TIME_TOOL');
  DBMS_CLOUD_AI_AGENT.CREATE_TOOL(
    tool_name => 'GET_DATABASE_CURRENT_TIME_TOOL',
    attributes => '{"instruction":"Get database current time (SYSTIMESTAMP/SYSDATE) and timezone values. Use this to resolve relative date requests like today/yesterday/last day.","function":"select_ai_scheduler_monitor.get_database_current_time"}',
    description => 'Get database current timestamp and timezone'
  );

  drop_tool_if_exists('LIST_ALL_JOBS_TOOL');
  DBMS_CLOUD_AI_AGENT.CREATE_TOOL(
    tool_name => 'LIST_ALL_JOBS_TOOL',
    attributes => '{"instruction":"List all scheduler jobs in the current schema with state, schedule, run/failure counts, and control attributes. For full-list requests, return complete rows/job names (do not sample), do not abbreviate with ellipsis, and set top_n high enough to cover all jobs.","function":"select_ai_scheduler_monitor.list_all_jobs"}',
    description => 'List all scheduler jobs in current schema'
  );

  drop_tool_if_exists('LIST_RUNNING_JOBS_TOOL');
  DBMS_CLOUD_AI_AGENT.CREATE_TOOL(
    tool_name => 'LIST_RUNNING_JOBS_TOOL',
    attributes => '{"instruction":"List currently running scheduler jobs with session, elapsed, cpu and destination details.","function":"select_ai_scheduler_monitor.list_running_jobs"}',
    description => 'List running scheduler jobs'
  );

  drop_tool_if_exists('LIST_JOB_HISTORY_TOOL');
  DBMS_CLOUD_AI_AGENT.CREATE_TOOL(
    tool_name => 'LIST_JOB_HISTORY_TOOL',
    attributes => '{"instruction":"Return historical scheduler job runs for the requested interval with status, duration, cpu, and error details.","function":"select_ai_scheduler_monitor.list_job_history"}',
    description => 'List scheduler job run history'
  );

  drop_tool_if_exists('GET_JOB_DETAILS_TOOL');
  DBMS_CLOUD_AI_AGENT.CREATE_TOOL(
    tool_name => 'GET_JOB_DETAILS_TOOL',
    attributes => '{"instruction":"Return full metadata and recent history for a selected scheduler job.","function":"select_ai_scheduler_monitor.get_job_details"}',
    description => 'Get scheduler job detail view'
  );

  drop_tool_if_exists('ANALYZE_CPU_BY_JOB_TOOL');
  DBMS_CLOUD_AI_AGENT.CREATE_TOOL(
    tool_name => 'ANALYZE_CPU_BY_JOB_TOOL',
    attributes => '{"instruction":"Analyze CPU usage by scheduler job over an interval; include top cpu consumers and cpu-to-elapsed ratio.","function":"select_ai_scheduler_monitor.analyze_cpu_by_job"}',
    description => 'Analyze per-job CPU usage'
  );

  drop_tool_if_exists('ANALYZE_LOAD_BY_JOB_TOOL');
  DBMS_CLOUD_AI_AGENT.CREATE_TOOL(
    tool_name => 'ANALYZE_LOAD_BY_JOB_TOOL',
    attributes => '{"instruction":"Analyze execution/load trends by minute/hour/day over an interval and provide inferred load correlation.","function":"select_ai_scheduler_monitor.analyze_load_by_job"}',
    description => 'Analyze scheduler load trends'
  );

  drop_tool_if_exists('COMPARE_JOBS_TOOL');
  DBMS_CLOUD_AI_AGENT.CREATE_TOOL(
    tool_name => 'COMPARE_JOBS_TOOL',
    attributes => '{"instruction":"Compare two jobs for runs, failures, average/p95 elapsed and cpu metrics.","function":"select_ai_scheduler_monitor.compare_jobs"}',
    description => 'Compare two scheduler jobs'
  );

  drop_tool_if_exists('IDENTIFY_HOTSPOTS_TOOL');
  DBMS_CLOUD_AI_AGENT.CREATE_TOOL(
    tool_name => 'IDENTIFY_HOTSPOTS_TOOL',
    attributes => '{"instruction":"Identify cpu/runtime hotspots and contention candidates across scheduler jobs.","function":"select_ai_scheduler_monitor.identify_hotspots"}',
    description => 'Identify scheduler hotspots'
  );

  drop_tool_if_exists('DETECT_FAILURES_TOOL');
  DBMS_CLOUD_AI_AGENT.CREATE_TOOL(
    tool_name => 'DETECT_FAILURES_TOOL',
    attributes => '{"instruction":"Detect recurring failures, common errors, and failure-prone jobs in the interval.","function":"select_ai_scheduler_monitor.detect_failures"}',
    description => 'Detect scheduler failures'
  );

  drop_tool_if_exists('SUMMARIZE_SCHEDULER_HEALTH_TOOL');
  DBMS_CLOUD_AI_AGENT.CREATE_TOOL(
    tool_name => 'SUMMARIZE_SCHEDULER_HEALTH_TOOL',
    attributes => '{"instruction":"Return scheduler health overview with executive summary, top cpu jobs, top failed jobs, and recommendations.","function":"select_ai_scheduler_monitor.summarize_scheduler_health"}',
    description => 'Summarize scheduler health'
  );

  drop_tool_if_exists('GENERATE_CHARTS_TOOL');
  DBMS_CLOUD_AI_AGENT.CREATE_TOOL(
    tool_name => 'GENERATE_CHARTS_TOOL',
    attributes => '{"instruction":"Generate chart-ready datasets/specifications for scheduler performance and reliability analysis.","function":"select_ai_scheduler_monitor.generate_charts"}',
    description => 'Generate chart datasets'
  );

  drop_tool_if_exists('EXPORT_TABLES_TOOL');
  DBMS_CLOUD_AI_AGENT.CREATE_TOOL(
    tool_name => 'EXPORT_TABLES_TOOL',
    attributes => '{"instruction":"Return export-friendly table payloads for running jobs, history, cpu, and failures.","function":"select_ai_scheduler_monitor.export_tables"}',
    description => 'Export scheduler analysis tables'
  );

  DBMS_OUTPUT.PUT_LINE('initialize_scheduler_tools completed.');
END initialize_scheduler_tools;
/

BEGIN
  initialize_scheduler_tools;
END;
/

ALTER SESSION SET CURRENT_SCHEMA = ADMIN;

PROMPT DBMS_SCHEDULER monitoring tools installation completed
