  CREATE TABLE "CIS_IAM_POLICIES"
   (	"ID" VARCHAR2(4000),
	"NAME" VARCHAR2(4000),
	"DEEP_LINK" VARCHAR2(4000),
	"COMPARTMENT_ID" VARCHAR2(4000),
	"DESCRIPTION" VARCHAR2(4000),
	"LIFECYCLE_STATE" VARCHAR2(4000),
	"STATMENTS" VARCHAR2(4000),
	"EXTRACT_DATE" TIMESTAMP (6)
   ) ;
/
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CIS_IAM_POLICIES_SV" ("CONTEXT_PROMPT") AS
  SELECT LISTAGG(PROMPT, '; ' ON OVERFLOW TRUNCATE ) AS CONTEXT_PROMPT FROM (SELECT 'Policy Name : '||NAME || 'Policy Statement : '|| STATMENTS as prompt FROM CIS_IAM_POLICIES);
/
  CREATE TABLE "CLOUDGUARD02_LISTPROBLEMS"
   (	"ID" VARCHAR2(32767),
	"LOCKS" VARCHAR2(32767),
	"LABELS" CLOB,
	"REGION" VARCHAR2(32767),
	"REGIONS" CLOB,
	"TIMEDUE" VARCHAR2(32767),
	"TARGETID" VARCHAR2(32767),
	"RISKLEVEL" VARCHAR2(32767),
	"RISKSCORE" VARCHAR2(32767),
	"DETECTORID" VARCHAR2(32767),
	"MANAGETYPE" VARCHAR2(32767),
	"RESOURCEID" VARCHAR2(32767),
	"RESOURCENAME" VARCHAR2(32767),
	"RESOURCETYPE" VARCHAR2(32767),
	"COMPARTMENTID" VARCHAR2(32767),
	"DETECTORRULEID" VARCHAR2(32767),
	"LIFECYCLESTATE" VARCHAR2(32767),
	"LIFECYCLEDETAIL" VARCHAR2(32767),
	"TIMELASTDETECTED" TIMESTAMP (6) WITH TIME ZONE,
	"TIMEFIRSTDETECTED" TIMESTAMP (6) WITH TIME ZONE
   ) ;
/
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CLOUDGUARD02_PROBLEMS_SV" ("CONTEXT_PROMPT") AS
  SELECT
        LISTAGG(prompt, '; ' ON OVERFLOW TRUNCATE) AS context_prompt
    FROM
        (
            SELECT
                'LABELS : '
                || LABELS || ' '
                || 'CLOUD GUARD DETECTOR NAME : '
                || DETECTORRULEID || ' '
                || 'RISKLEVEL : '
                || RISKLEVEL || ' '
                || 'RESOURCE NAME : '
                || RESOURCENAME || ' '
                || 'RESOURCE TYPE : '
                || RESOURCETYPE ||  ';' AS prompt
            FROM
                cloudguard02_listproblems
            WHERE RISKLEVEL='CRITICAL'
        );
/
  CREATE TABLE "LISTHOSTINSIGHTS"
   (	"ID" VARCHAR2(32767),
	"ROOTID" VARCHAR2(32767),
	"STATUS" VARCHAR2(32767),
	"HOSTNAME" VARCHAR2(32767),
	"HOSTTYPE" VARCHAR2(32767),
	"PARENTID" VARCHAR2(32767),
	"COMPUTEID" VARCHAR2(32767),
	"RESOURCEDATE" TIMESTAMP (6) WITH TIME ZONE,
	"RESOURCEOWNER" VARCHAR2(32767),
	"TIMECREATED" TIMESTAMP (6) WITH TIME ZONE,
	"TIMEUPDATED" TIMESTAMP (6) WITH TIME ZONE,
	"ENTITYSOURCE" VARCHAR2(32767),
	"PLATFORMTYPE" VARCHAR2(32767),
	"COMPARTMENTID" VARCHAR2(32767),
	"LIFECYCLESTATE" VARCHAR2(32767),
	"PROCESSORCOUNT" VARCHAR2(32767),
	"HOSTDISPLAYNAME" VARCHAR2(32767),
	"LIFECYCLEDETAILS" VARCHAR2(32767),
	"MANAGEMENTAGENTID" VARCHAR2(32767),
	"OPSIPRIVATEENDPOINTID" VARCHAR2(32767),
	 CONSTRAINT "LISTHOSTINSIGHTS_PK" PRIMARY KEY ("HOSTNAME")
  USING INDEX  ENABLE
   ) ;
/
  CREATE TABLE "HOSTINSIGHTS_RES_STAT"
   (	"ID" VARCHAR2(32767),
	"HOSTNAME" VARCHAR2(32767),
	"PLATFORMTYPE" VARCHAR2(32767),
	"COMPARTMENTID" VARCHAR2(32767),
	"AGENTIDENTIFIER" VARCHAR2(32767),
	"HOSTDISPLAYNAME" VARCHAR2(32767),
	"MEDIAN" NUMBER,
	"AVERAGE" NUMBER,
	"MAXIMUM" NUMBER,
	"MINIMUM" NUMBER,
	"LOWERQUARTILE" NUMBER,
	"UPPERQUARTILE" NUMBER,
	"USAGE" NUMBER,
	"CAPACITY" VARCHAR2(32767),
	"RESOURCENAME" VARCHAR2(32767),
	"USAGECHANGEPERCENT" NUMBER,
	"UTILIZATIONPERCENT" NUMBER,
	 CONSTRAINT "HOSTINSIGHTS_RES_STAT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;
/

  CREATE TABLE "HOSTINSIGHTS_REPORT_PERIOD"
   (	"USAGEUNIT" VARCHAR2(32767),
	"RESOURCEMETRIC" VARCHAR2(32767),
	"TIMEINTERVALEND" TIMESTAMP (6) WITH TIME ZONE,
	"TIMEINTERVALSTART" TIMESTAMP (6) WITH TIME ZONE,
	"ID" VARCHAR2(4000)
   ) ;
/
  CREATE TABLE "HOSTCONFIG"
   (	"HOSTNAME" VARCHAR2(32767),
	"PARENTID" VARCHAR2(32767),
	"COMPUTEID" VARCHAR2(32767),
	"CPUVENDOR" VARCHAR2(32767),
	"TOTALCPUS" NUMBER,
	"CONNECTORID" VARCHAR2(32767),
	"RESOURCEDATE" TIMESTAMP (6) WITH TIME ZONE,
	"RESOURCEOWNER" VARCHAR2(32767),
	"ENTITYSOURCE" VARCHAR2(32767),
	"PLATFORMTYPE" VARCHAR2(32767),
	"TOTALSOCKETS" NUMBER,
	"COMPARTMENTID" VARCHAR2(32767),
	"CPUCACHEINMBS" NUMBER,
	"HOSTINSIGHTID" VARCHAR2(32767),
	"CORESPERSOCKET" NUMBER,
	"ID" VARCHAR2(32767),
	"NAME" VARCHAR2(32767),
	"PLATFORMVENDOR" VARCHAR2(32767),
	"CPUARCHITECTURE" VARCHAR2(32767),
	"PLATFORMVERSION" VARCHAR2(32767),
	"THREADSPERSOCKET" NUMBER,
	"TOTALMEMORYINGBS" NUMBER,
	"CPUFREQUENCYINMHZ" NUMBER,
	"CPUIMPLEMENTATION" VARCHAR2(32767),
	"MANAGEMENTAGENTID" VARCHAR2(32767),
	"OPSIPRIVATEENDPOINTID" VARCHAR2(32767),
	"ISHYPERTHREADINGENABLED" VARCHAR2(32767),
	"APEX$SYNC_STEP_STATIC_ID" VARCHAR2(255),
	"APEX$ROW_SYNC_TIMESTAMP" TIMESTAMP (6) WITH TIME ZONE,
	"TIMEINTERVALSTART" DATE,
	"TIMEINTERVALEND" DATE,
	"RESOURCEMETRIC" VARCHAR2(4000),
	"PATTERN" VARCHAR2(4000),
	"HISTORICALDATA" CLOB,
	"PROJECTEDDATA" CLOB
   ) ;
/

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "HOSTINSIGHTS_REPORT_SV" ("CONTEXT_PROMPT") AS
  SELECT
    LISTAGG(prompt, '; ' ON OVERFLOW TRUNCATE) AS context_prompt
FROM
    (
        SELECT
            'Host name : ' || LISTHOSTINSIGHTS.HOSTNAME || ' ; ' ||
            'Time Interval Start : ' || HOSTINSIGHTS_REPORT_PERIOD.TIMEINTERVALSTART || ' ; ' ||
            'Time Interval End : ' || HOSTINSIGHTS_REPORT_PERIOD.TIMEINTERVALEND || ' ; ' ||
            'Platform Type : ' || HOSTINSIGHTS_RES_STAT.PLATFORMTYPE || ' ; ' ||
            'CPU Vendor : ' || HOSTCONFIG.CPUVENDOR || ' ; ' ||
            'Total CPUs : ' || HOSTCONFIG.TOTALCPUS || ' ; ' ||
            'Total Sockets : ' || HOSTCONFIG.TOTALSOCKETS || ' ; ' ||
            'CPU Cache (MB) : ' || HOSTCONFIG.CPUCACHEINMBS || ' ; ' ||
            'Cores Per Socket : ' || HOSTCONFIG.CORESPERSOCKET || ' ; ' ||
            'CPU Architecture : ' || HOSTCONFIG.CPUARCHITECTURE || ' ; ' ||
            'Platform Version : ' || HOSTCONFIG.PLATFORMVERSION || ' ; ' ||
            'Threads Per Socket : ' || HOSTCONFIG.THREADSPERSOCKET || ' ; ' ||
            'Total Memory (GB) : ' || HOSTCONFIG.TOTALMEMORYINGBS || ' ; ' ||
            'CPU Frequency (MHz) : ' || HOSTCONFIG.CPUFREQUENCYINMHZ || ' ; ' ||
            'CPU Implementation : ' || HOSTCONFIG.CPUIMPLEMENTATION || ' ; ' ||
            'Hyperthreading Enabled : ' || HOSTCONFIG.ISHYPERTHREADINGENABLED || ' ; ' ||
            'Median Usage : ' || HOSTINSIGHTS_RES_STAT.MEDIAN || ' ; ' ||
            'Average Usage : ' || HOSTINSIGHTS_RES_STAT.AVERAGE || ' ; ' ||
            'Maximum Usage : ' || HOSTINSIGHTS_RES_STAT.MAXIMUM || ' ; ' ||
            'Minimum Usage : ' || HOSTINSIGHTS_RES_STAT.MINIMUM || ' ; ' ||
            'Lower Quartile : ' || HOSTINSIGHTS_RES_STAT.LOWERQUARTILE || ' ; ' ||
            'Upper Quartile : ' || HOSTINSIGHTS_RES_STAT.UPPERQUARTILE || ' ; ' ||
            'Usage : ' || HOSTINSIGHTS_RES_STAT.USAGE || ' ; ' ||
            'Capacity : ' || HOSTINSIGHTS_RES_STAT.CAPACITY || ' ; ' ||
            'Usage Change Percent : ' || HOSTINSIGHTS_RES_STAT.USAGECHANGEPERCENT || ' ; ' ||
            'Utilization Percent : ' || HOSTINSIGHTS_RES_STAT.UTILIZATIONPERCENT || ' ; ' ||
            'Host Type : ' || LISTHOSTINSIGHTS.HOSTTYPE || ' ; ' ||
            'Lifecycle State : ' || LISTHOSTINSIGHTS.LIFECYCLESTATE AS prompt
        FROM
            LISTHOSTINSIGHTS LISTHOSTINSIGHTS,
            HOSTINSIGHTS_RES_STAT HOSTINSIGHTS_RES_STAT,
            HOSTINSIGHTS_REPORT_PERIOD HOSTINSIGHTS_REPORT_PERIOD,
            HOSTCONFIG
        WHERE LISTHOSTINSIGHTS.HOSTNAME =hostinsights_res_stat.hostname
            and HOSTCONFIG.HOSTNAME = LISTHOSTINSIGHTS.HOSTNAME
    );
/

  CREATE TABLE "OCI_DOC_REF"
   (	"CATEGORY" VARCHAR2(4000),
	"SHORT_DESCRIPTION" VARCHAR2(4000),
	"SUMMARY" VARCHAR2(4000),
	"OCI_DOC_URL" VARCHAR2(4000),
	"USE_CASE" VARCHAR2(4000),
	"PERSONA" VARCHAR2(4000),
	"VERSION" VARCHAR2(4000),
	"LAST_UPDATED_DATE" TIMESTAMP (6),
	"KEY_FEATURES" VARCHAR2(4000)
   ) ;
/

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "OCI_DOC_REF_COMPUTE_SV" ("CONTEXT_PROMPT") AS
  SELECT
    LISTAGG(prompt, '; ' ON OVERFLOW TRUNCATE) AS context_prompt
FROM
    (
        SELECT
            'Category: ' || CATEGORY || ' ; ' ||
            'Short Description: ' || SHORT_DESCRIPTION || ' ; ' ||
            'Summary: ' || SUMMARY || ' ; ' ||
            'OCI Documentation URL: ' || OCI_DOC_URL || ' ; ' ||
            'Use Case: ' || USE_CASE || ' ; ' ||
            'Persona: ' || PERSONA || ' ; ' ||
            'Version: ' || VERSION || ' ; ' ||
            'Last Updated Date: ' || LAST_UPDATED_DATE || ' ; ' ||
            'Key Features: ' || KEY_FEATURES AS prompt
        FROM
            OCI_DOC_REF
        WHERE category = 'Compute'
    );
/
  CREATE TABLE "OCI_CDB"
   (	"CDB_ID" NUMBER,
	"NAME" VARCHAR2(100),
	"REGION" VARCHAR2(100),
	"MULTICLOUD" VARCHAR2(100),
	 PRIMARY KEY ("CDB_ID")
  USING INDEX  ENABLE
   ) ;
/
  CREATE TABLE "OCI_PDB"
   (	"PDB_ID" NUMBER,
	"NAME" VARCHAR2(100),
	"REGION" VARCHAR2(100),
	"MULTICLOUD" VARCHAR2(100),
	 PRIMARY KEY ("PDB_ID")
  USING INDEX  ENABLE
   ) ;
/
  CREATE TABLE "OCI_EXA_INFR"
   (	"EXA_INFRA_ID" NUMBER,
	"NAME" VARCHAR2(100),
	"REGION" VARCHAR2(100),
	"MULTICLOUD" VARCHAR2(100),
	 PRIMARY KEY ("EXA_INFRA_ID")
  USING INDEX  ENABLE
   ) ;
/
  CREATE TABLE "OCI_EXA_VM_CLUSTER"
   (	"VM_CLUSTER_ID" NUMBER,
	"NAME" VARCHAR2(100),
	"REGION" VARCHAR2(100),
	"MULTICLOUD" VARCHAR2(100),
	 PRIMARY KEY ("VM_CLUSTER_ID")
  USING INDEX  ENABLE
   ) ;
/
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CIS_MULTICLOUD_DETAILS_V" ("CONTEXT_PROMPT") AS
  SELECT
        LISTAGG(prompt, '; ' ON OVERFLOW TRUNCATE) AS context_prompt
    FROM
        (
            SELECT
                'CDB name : '
                || cdb.name || ' '
                || 'CDB region : '
                || cdb.region || ' '
                || 'CDB multicloud type : '
                || cdb.multicloud || ' ' as prompt
            FROM
                oci_cdb cdb
            UNION
            SELECT
                'PDB name : '
                || pdb.name || ' '
                || 'PDB region : '
                || pdb.region || ' '
                || 'PDB multicloud type : '
                || pdb.multicloud || ' ' as prompt
            FROM
                oci_pdb pdb
            UNION
            SELECT
                'Exa VM Cluster name : '
                || vmclu.name || ' '
                || 'Exa VM Cluster  region : '
                || vmclu.region || ' '
                || 'Exa VM Cluster  multicloud type : '
                || vmclu.multicloud || ' ' as prompt
            FROM
                oci_exa_vm_cluster vmclu
            UNION
            SELECT
                'Exadata Infrastructure name : '
                || exa.name || ' '
                || 'Exadata Infrastructure region : '
                || exa.region || ' '
                || 'Exadata Infrastructure multicloud type : '
                || exa.multicloud || ' ' AS prompt
            FROM
                oci_exa_infr exa
        );
/
  CREATE TABLE "HOSTINSIGHTS_CPU_USAGE_SUMMARY"
   (	"TIMEINTERVALSTART" DATE,
	"TIMEINTERVALEND" DATE,
	"USAGE" NUMBER,
	"USAGEUNIT" VARCHAR2(4000),
	"CAPACITY" NUMBER,
	"USAGECHANGEPERCENT" NUMBER
   ) ;
/
  CREATE TABLE "HOSTINSIGHTS_MEMORY_USAGE_SUMMARY"
   (	"TIMEINTERVALSTART" DATE,
	"TIMEINTERVALEND" DATE,
	"USAGE" NUMBER,
	"USAGEUNIT" VARCHAR2(4000),
	"CAPACITY" NUMBER,
	"USAGECHANGEPERCENT" NUMBER
   ) ;
/
  CREATE TABLE "HOSTINSIGHTS_MEMORY_USAGE_TREND"
   (	"TIMEINTERVALSTART" DATE,
	"TIMEINTERVALEND" DATE,
	"RESOURCEMETRIC" VARCHAR2(4000),
	"USAGEUNIT" VARCHAR2(4000),
	"ITEMDURATIONINMS" NUMBER,
	"USAGEDATA" CLOB
   ) ;
/
  CREATE TABLE "HOSTINSIGHTS_RES_STAT_MEMORY"
   (	"ID" VARCHAR2(32767),
	"HOSTNAME" VARCHAR2(32767),
	"PLATFORMTYPE" VARCHAR2(32767),
	"COMPARTMENTID" VARCHAR2(32767),
	"AGENTIDENTIFIER" VARCHAR2(32767),
	"HOSTDISPLAYNAME" VARCHAR2(32767),
	"MEDIAN" NUMBER,
	"AVERAGE" NUMBER,
	"MAXIMUM" NUMBER,
	"MINIMUM" NUMBER,
	"LOWERQUARTILE" NUMBER,
	"UPPERQUARTILE" NUMBER,
	"USAGE" NUMBER,
	"CAPACITY" VARCHAR2(32767),
	"RESOURCENAME" VARCHAR2(32767),
	"USAGECHANGEPERCENT" NUMBER,
	"UTILIZATIONPERCENT" NUMBER,
	 CONSTRAINT "HOSTINSIGHTS_RES_STAT_MEMORY_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;
/
  CREATE TABLE "HOSTINSIGHTS_CPU_FORECAST_TREND"
   (	"TIMEINTERVALSTART" DATE,
	"TIMEINTERVALEND" DATE,
	"RESOURCEMETRIC" VARCHAR2(4000),
	"PATTERN" VARCHAR2(4000),
	"HISTORICALDATA" CLOB,
	"PROJECTEDDATA" CLOB
   ) ;
/
  CREATE TABLE "CDB_PDB_GRAPH_KEY$"
   (	"COLUMN_NAME" VARCHAR2(128),
	"COLUMN_NUMBER" NUMBER,
	"KEY_TYPE" VARCHAR2(6),
	"ET_NAME" VARCHAR2(128),
	 CONSTRAINT "CDB_PDB_GRAPH_KEY$_PK" PRIMARY KEY ("COLUMN_NAME", "KEY_TYPE", "ET_NAME")
  USING INDEX  ENABLE
   ) ;
/
  CREATE TABLE "CDB_PDB_GRAPH_LABEL$"
   (	"LABEL_NAME" VARCHAR2(128),
	"ET_NAME" VARCHAR2(128),
	"ET_TYPE" VARCHAR2(6),
	 CONSTRAINT "CDB_PDB_GRAPH_LABEL$_PK" PRIMARY KEY ("LABEL_NAME", "ET_NAME", "ET_TYPE")
  USING INDEX  ENABLE
   ) ;
/
  CREATE TABLE "CDB_PDB_GRAPH_PROPERTY$"
   (	"PROPERTY_NAME" VARCHAR2(128),
	"ET_NAME" VARCHAR2(128),
	"ET_TYPE" VARCHAR2(6),
	"LABEL_NAME" VARCHAR2(128),
	"COLUMN_NAME" VARCHAR2(128),
	 CONSTRAINT "CDB_PDB_GRAPH_PROPERTY$_PK" PRIMARY KEY ("PROPERTY_NAME", "ET_NAME", "LABEL_NAME")
  USING INDEX  ENABLE
   ) ;
/
  CREATE TABLE "CDB_PDB_GRAPH_SRC_DST_KEY$"
   (	"ET_NAME" VARCHAR2(128),
	"VT_NAME" VARCHAR2(128),
	"KEY_TYPE" VARCHAR2(16),
	"ET_COLUMN_NAME" VARCHAR2(128),
	"ET_COLUMN_NUMBER" NUMBER,
	"VT_COLUMN_NAME" VARCHAR2(128),
	 CONSTRAINT "CDB_PDB_GRAPH_SRC_DST_KEY$_PK" PRIMARY KEY ("ET_NAME", "VT_NAME", "KEY_TYPE", "ET_COLUMN_NAME")
  USING INDEX  ENABLE
   ) ;
/
create or replace PACKAGE DBMS_GVT
  AUTHID CURRENT_USER IS
 -----------------------------------------------------------------------------
 -- VERTEX_LATERAL_STRING - prepare vertex query string in LATERAL()
 -----------------------------------------------------------------------------
  FUNCTION PROPERTIES_LATERAL_STRING (
    DB_TABLE_NAME_LIST SYS.ODCIVARCHAR2LIST,
    DB_OBJECT_OWNER_LIST SYS.ODCIVARCHAR2LIST,
    GRAPH_VIZ_TABLE_NAME IN VARCHAR2,
    VERTEX_ID_COL_NAME IN VARCHAR2,
    GRAPHNAME IN VARCHAR2,
    GRAPHOWNER IN VARCHAR2,
    ELEMENT_TYPE IN VARCHAR2
  ) RETURN VARCHAR2;
 -----------------------------------------------------------------------------
 -- EDGE_LATERAL_STRING - prepare edge subquery string in LATERAL()
 -----------------------------------------------------------------------------
  FUNCTION EDGE_LATERAL_STRING (
    DB_TABLE_NAME_LIST SYS.ODCIVARCHAR2LIST,
    DB_OBJECT_OWNER_LIST SYS.ODCIVARCHAR2LIST,
    EDGE_ELEMENT_NAME SYS.ODCIVARCHAR2LIST,
    GRAPH_VIZ_TABLE_NAME IN VARCHAR2,
    EDGE_ID_COL_NAME IN VARCHAR2,
    GRAPHNAME IN VARCHAR2,
    GRAPHOWNER IN VARCHAR2
  ) RETURN CLOB;

  FUNCTION GET_VERSION RETURN VARCHAR2;

 -----------------------------------------------------------------------------
 -- BUILD_JSON - prepare JSON result from vertex_id and edge_id tables
 -----------------------------------------------------------------------------
  FUNCTION BUILD_JSON(
      VERTEX_TABLE SYS.ODCIRIDLIST,
      EDGE_TABLE SYS.ODCIRIDLIST,
      COUNTER NUMBER,
      GRAPHNAME VARCHAR2,
      GRAPHOWNER VARCHAR2
  ) RETURN CLOB;

END DBMS_GVT;
/
create or replace FUNCTION ORA_SQLGRAPH_TO_JSON (
  CURS_ID INTEGER,
  PAGE_START NUMBER DEFAULT NULL,
  PAGE_SIZE NUMBER DEFAULT NULL
) RETURN CLOB
  AUTHID CURRENT_USER IS
  M_VCSIZ_4K                              CONSTANT PLS_INTEGER := 4000;
  M_VCSIZ_32K                             CONSTANT PLS_INTEGER := 32672;
  JSON_FILE                               CLOB; --the returned result
  GRAPHNAME                               VARCHAR2(M_VCSIZ_4K);
  ELEMENT_NAME                            VARCHAR2(M_VCSIZ_4K);
  GRAPHOWNER                              VARCHAR2(M_VCSIZ_4K);
  L_COLS                                  INTEGER;
  TAB_REC                                 SYS.DBMS_SQL.DESC_TAB;
  CUR                                     SYS_REFCURSOR;
  L_FLAG                                  NUMBER;
  L_JSON                                  VARCHAR2(M_VCSIZ_4K);
  VERTEX_ID_COLUMN_LIST                   SYS.ODCINUMBERLIST := SYS.ODCINUMBERLIST();
  EDGE_ID_COLUMN_LIST                     SYS.ODCINUMBERLIST := SYS.ODCINUMBERLIST();
  P1                                      NUMBER := 1;
  V1                                      NUMBER := 1;
  E1                                      NUMBER := 1;
  VERTEX_TABLE                            SYS.ODCIRIDLIST := SYS.ODCIRIDLIST();
  EDGE_TABLE                              SYS.ODCIRIDLIST := SYS.ODCIRIDLIST();
  V2                                      NUMBER := 1;
  E2                                      NUMBER := 1;
  L_HAVING_ELEMENT_ID                     BOOLEAN := FALSE;
  COUNTER                                 NUMBER := 0;
BEGIN
  SYS.DBMS_SQL.DESCRIBE_COLUMNS(
    C => CURS_ID,
    COL_CNT => L_COLS,
    DESC_T => TAB_REC
  );

  FOR POS IN 1 .. L_COLS LOOP
    CASE TAB_REC (POS).COL_TYPE
      WHEN 119 THEN
        SYS.DBMS_SQL.DEFINE_COLUMN (CURS_ID, POS, L_JSON, 2000);
      ELSE
        NULL;
    END CASE;
  END LOOP;

  WHILE SYS.DBMS_SQL.FETCH_ROWS (CURS_ID) != 0 LOOP
    COUNTER := COUNTER + 1;
    IF ((PAGE_START < 0
    OR PAGE_SIZE <= 0)
    AND (PAGE_START IS NOT NULL
    AND PAGE_SIZE IS NOT NULL)) THEN
      RAISE_APPLICATION_ERROR(-20000, 'Please provide valid values for page_start and page_size parameter. page_start should be an integer equal to or greater than 0. page_size should be an integer greater than 0');
    END IF;

    IF ((COUNTER > PAGE_START
    AND COUNTER <= PAGE_START + PAGE_SIZE)
    OR (PAGE_START IS NULL
    AND PAGE_START IS NULL) ) THEN
      IF P1 = 1 THEN
        FOR POS IN 1 .. L_COLS LOOP
          IF TAB_REC(POS).COL_TYPE = 119 THEN
            SYS.DBMS_SQL.COLUMN_VALUE (CURS_ID, POS, L_JSON);

            IF JSON_EXISTS(L_JSON, '$.ELEM_TABLE') AND JSON_EXISTS(L_JSON, '$.GRAPH_OWNER') AND JSON_EXISTS(L_JSON, '$.GRAPH_NAME') AND JSON_EXISTS(L_JSON, '$.KEY_VALUE') THEN
              L_HAVING_ELEMENT_ID := TRUE;
              IF GRAPHNAME IS NULL AND GRAPHOWNER IS NULL THEN
                GRAPHNAME := JSON_VALUE(L_JSON, '$.GRAPH_NAME');
                GRAPHOWNER := JSON_VALUE(L_JSON, '$.GRAPH_OWNER');
              END IF;

              SELECT
                ELEMENT_KIND INTO ELEMENT_NAME
              FROM
                SYS.ALL_PG_ELEMENTS
              WHERE
                ELEMENT_NAME = JSON_VALUE(L_JSON, '$.ELEM_TABLE')
                AND GRAPH_NAME = GRAPHNAME
                AND OWNER = GRAPHOWNER;
              IF ELEMENT_NAME = 'VERTEX' THEN
                VERTEX_ID_COLUMN_LIST.EXTEND;
                VERTEX_ID_COLUMN_LIST(V1) := POS;
                V1 := V1 + 1;
                VERTEX_TABLE.EXTEND();
                VERTEX_TABLE(V2) := L_JSON;
                V2 := V2 + 1;
              ELSE
                EDGE_ID_COLUMN_LIST.EXTEND;
                EDGE_ID_COLUMN_LIST(E1) := POS;
                E1 := E1 + 1;
                EDGE_TABLE.EXTEND();
                EDGE_TABLE(E2) := L_JSON;
                E2 := E2 + 1;
              END IF;
            END IF;
          END IF;
        END LOOP;
      ELSE
        FOR I IN 1..VERTEX_ID_COLUMN_LIST.COUNT LOOP
          IF V2 = 32768 THEN
            RAISE_APPLICATION_ERROR(-20000,'The number of vertices in the result set exceeds the limit of 32767. Add FETCH/OFFSET clauses to your query or set the page size parameters of the ORA_SQLGRAPH_TO_JSON function to reduce the result size.');
          END IF;
          SYS.DBMS_SQL.COLUMN_VALUE (CURS_ID, VERTEX_ID_COLUMN_LIST(I), L_JSON);
          VERTEX_TABLE.EXTEND();
          VERTEX_TABLE(V2) := L_JSON;
          V2 := V2 + 1;
        END LOOP;

        FOR I IN 1..EDGE_ID_COLUMN_LIST.COUNT LOOP
          IF E2 = 32768 THEN
            RAISE_APPLICATION_ERROR(-20000,'The number of edges in the result set exceeds the limit of 32767. Add FETCH/OFFSET clauses to your query or set the page size parameters of the ORA_SQLGRAPH_TO_JSON function to reduce the result size.');
          END IF;
          SYS.DBMS_SQL.COLUMN_VALUE (CURS_ID, EDGE_ID_COLUMN_LIST(I), L_JSON);
          EDGE_TABLE.EXTEND();
          EDGE_TABLE(E2) := L_JSON;
          E2 := E2 + 1;
        END LOOP;
      END IF;

      P1 := P1 + 1;
    END IF;
  END LOOP;

  IF NOT L_HAVING_ELEMENT_ID AND COUNTER != 0 THEN
    RAISE_APPLICATION_ERROR(-20000, 'Please add vertex_id/edge_id in both the COLUMNS and SELECT clause');
  END IF;
    JSON_FILE := DBMS_GVT.BUILD_JSON(VERTEX_TABLE, EDGE_TABLE, COUNTER, GRAPHNAME, GRAPHOWNER);
  RETURN JSON_FILE;
END ORA_SQLGRAPH_TO_JSON;
/
